### ISSUE TITLE
现在aws  kvm的 一d一个失联....

### ISSUE THREAD

**Issue by iovejieba** [bin456789/reinstall#101]
现在aws  kvm的机器D win 一d一个失联.... 
各位大佬有啥好方案么...阿里就没事  镜像都试过了 
aws 不管是手动指定ip网关 还是靠脚本自动获取 均失联

**Comment by bin456789** [comment]
你确定用的是这个脚本？
这个脚本没有 "手动指定ip网关" 这个功能

**Comment by iovejieba** [comment]
> 你确定用的是这个脚本？ 这个脚本没有 "手动指定ip网关" 这个功能

没 我意思是 手动指定ip的脚本 试过了 此项目也试过了

**Comment by bin456789** [comment]
目测你用的是dd模式，而镜像没有 aws ena 驱动
用iso模式的话应该不会失联

**Comment by iovejieba** [comment]
> 目测你用的是dd模式，而镜像没有 aws ena 驱动 用iso模式的话应该不会失联

xen的驱动么？ 老哥  kvm构架的也必须要xen么？

**Comment by bin456789** [comment]
> > 目测你用的是dd模式，而镜像没有 aws ena 驱动 用iso模式的话应该不会失联
> 
> xen的驱动么？ 老哥 kvm构架的也必须要xen么？

不是 xen
aws 的 kvm 需要专门的 ena 网卡驱动
https://docs.aws.amazon.com/zh_cn/AWSEC2/latest/WindowsGuide/enhanced-networking-ena.html

**Comment by iovejieba** [comment]
> > > 目测你用的是dd模式，而镜像没有 aws ena 驱动 用iso模式的话应该不会失联
> > 
> > 
> > xen的驱动么？ 老哥 kvm构架的也必须要xen么？
> 
> 不是 xen aws 的 kvm 需要专门的 ena 网卡驱动 https://docs.aws.amazon.com/zh_cn/AWSEC2/latest/WindowsGuide/enhanced-networking-ena.html

嗯 看到了 感谢 我去集成下  在d下看看 感谢！
