### ISSUE TITLE
vmlinuz-virt 资源404

### ISSUE THREAD

**Issue by XchenYa** [bin456789/reinstall#102]
该资源挂了导致脚本执行中断：
https://mirrors.ustc.edu.cn/alpine/v3.20/releases/x86_64/netboot/vmlinuz-virt
![image](https://github.com/bin456789/reinstall/assets/103161464/33806890-3095-4080-a1b4-f065ec454c8b)

**Comment by XchenYa** [comment]
修改为：
https://mirrors.ustc.edu.cn/alpine/v3.20/releases/x86_64/netboot-3.20.0/vmlinuz-virt
即可解决

**Comment by bin456789** [comment]
恢复正常了
