### ISSUE TITLE
azdd失败

### ISSUE THREAD

**Issue by AckerPaul** [bin456789/reinstall#103]
不是是报这个
Error: Line 587 return 1
    efi_row=$(lsblk /dev/$xda -ro NAME,PARTTYPE,PARTUUID | grep -i "$EFI_UUID")
   就是报这个
   partx: /dev/sda: failed to read partition table
[31mError: Line 157 return 1[0m
            partx -u $1

**Comment by bin456789** [comment]
说下你的命令

**Comment by AckerPaul** [comment]
bash reinstall.sh dd --img='win10ltsc_en_gen2.gz'

**Comment by AckerPaul** [comment]
az没有vnc只有诊断截图重启后镜像下载完成就报上面错

**Comment by AckerPaul** [comment]
一开始 用b系列的机子成功了2次 后面死活都不行了 什么系列都不行

**Comment by bin456789** [comment]
实际上已经d进硬盘了，只是将引导写入主板 nvram 的过程报错
可以无视错误，直接重启
如果重启后无法启动，那就是镜像的问题
