### ISSUE TITLE
移动云电脑自动获取的ip是空

### ISSUE THREAD

**Issue by clmzlb** [bin456789/reinstall#104]
移动云电脑自动获取的静态ip是空，导致后续安装报错，能否加个手动填写ip的功能，或者看下能否解决这个问题，半年前用--ci可以，现在也不行了。
![Image_1718945415662](https://github.com/bin456789/reinstall/assets/61145316/9ec74f76-70b3-40ca-b217-0dc78ddfcd33)
![Image_1718945412965](https://github.com/bin456789/reinstall/assets/61145316/57e89d7f-3a62-4d55-8983-6f49df6d2d0a)

**Comment by bin456789** [comment]
我没有云电脑，无法做测试
目前建议你在这行前面添加ip信息
https://github.com/bin456789/reinstall/blob/c682835af62ce5e4d51af2266f5d7f4c7681d126/reinstall.sh#L1671

ipv4_mac=xx:xx:xx:xx:xx:xx
ipv4_addr=1.2.3.4/24
ipv4_gateway=2.3.4.5

**Comment by clmzlb** [comment]
![Q_V$FOPSDNAVT%U406(EX5](https://github.com/bin456789/reinstall/assets/61145316/bbd2f0db-a7c6-4dc4-bace-86b137029a6f)
![J`PK2R}G9 _ 16SUV}MRJXB](https://github.com/bin456789/reinstall/assets/61145316/93801b61-916d-4799-bafc-f4a025df9251)
![_B6ZQN8YQ2 LBU Y`PZ5DOE](https://github.com/bin456789/reinstall/assets/61145316/323fd4c8-3936-41c6-b822-bff96f8437a7)
![image](https://github.com/bin456789/reinstall/assets/61145316/05474dd0-5d57-406d-b757-a503335d7c63)
还是不行，似乎没有找到网卡，我可以提供云电脑，有联系方式吗？

**Comment by bin456789** [comment]
bin456789@gmail.com

**Comment by clmzlb** [comment]
大佬已帮解决，代理原因，修改reinstall.sh的内置代理 github_proxy参数就好了

**Comment by RainNameless** [comment]
> 大佬已帮解决，代理原因，修改reinstall.sh的内置代理 github_proxy参数就好了

想咨询一下 政客版本的 云电脑能dd吗？
