### ISSUE TITLE
搬瓦工dd debian12 出现两个网卡选项，无法自动选择，会卡住

### ISSUE THREAD

**Issue by ezrawic4j** [bin456789/reinstall#11]
<img width="1028" alt="image" src="https://github.com/bin456789/reinstall/assets/121549438/c1d6b796-d659-4890-9161-7313d10c7f06">

求修复，到这一步会卡住，必须要进vnc操作

机器是前两天热门的46刀搬瓦工机器 1c 512m

**Comment by bin456789** [comment]
现已修复
