### ISSUE TITLE
支持自定义SSH端口

### ISSUE THREAD

**Issue by MiniGrayGay** [bin456789/reinstall#110]
挂机宝的Windows是hyper-v的虚拟机，12312映射到了3389，希望脚本能自定义Windows的远程桌面端口和Linux的SSH端口

**Comment by MiniGrayGay** [comment]
想用脚本重装成Ubuntu，但是找不到方法把SSH端口直接改为3389

**Comment by bin456789** [comment]
好神奇的需求，但又竟然合情合理
ubuntu的配置文件是 cloud-init.yaml
你可以 fork 改下 cloud-init.yaml 和 reinstall.sh 的 confhome

**Comment by ColinYYCC** [comment]
大老可以通过指令更改-port 啥的，沒有改的能力

**Comment by bin456789** [comment]
现在支持改端口了 `--ssh-port 3389`

**Comment by MiniGrayGay** [comment]
多谢大佬
