### ISSUE TITLE
dd到centos 7时遇到一个问题，发现里面那个网站已经502了，这里我贴一个日志，

### ISSUE THREAD

**Issue by AndraidAP270868441b4** [bin456789/reinstall#111]
/sbin/grubby
cpe:/o:centos:centos:7
cat: /dev/ipv6_has_internet: No such file or directory
cpe:/o:centos:centos:7
Loaded plugins: fastestmirror
Determining fastest mirrors
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=genclo error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
Error: Line 2129 return 1
            chroot /os/ yum -y --disablerepo=* --enablerepo=base,updates "$@"  
  
![image](https://github.com/bin456789/reinstall/assets/86146160/c5e6b08e-a35d-4bee-9d0a-2c9e1e22da78)

**Comment by bin456789** [comment]
centos 7 官方停止支持了，所以那个网址打不开

脚本也会删除 centos 7 支持

**Comment by Spark100k** [comment]
可以使用vault.centos.org
https://vault.centos.org/7.9.2009/os/x86_64/
https://vault.centos.org/7.9.2009/isos/x86_64/

**Comment by bin456789** [comment]
centos7停止维护了
建议用 anolis 7
脚本能安装
