### ISSUE TITLE
谷歌云一键安装失败。

### ISSUE THREAD

**Issue by bobby520** [bin456789/reinstall#113]
您好，谷歌云使用一键安装WINDOWS最后会一直循环在下面的提示，请问如何解决，谢谢！！
![C0382772-8FF5-4566-82C1-1BC1377672C7](https://github.com/bin456789/reinstall/assets/78472812/61d25dd0-5e66-4c99-abc7-0ecac8d25396)

**Comment by bin456789** [comment]
已知问题，这个 issue 就先关闭了
https://github.com/bin456789/reinstall/issues/108
