### ISSUE TITLE
建议国内脚本加上代理

### ISSUE THREAD

**Issue by xkatld** [bin456789/reinstall#114]
错误：
`
https://raw.githubusercontent.com/bin456789/reinstall/main/trans.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  2166    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Error: Line 2556 return 22
    curl -Lo $tmp_dir/trans.sh $confhome/trans.sh
`
解决方法：
`
confhome=https://mirror.ghproxy.com/https://raw.githubusercontent.com/bin456789/reinstall/main
github_proxy=https://mirror.ghproxy.com/https://raw.githubusercontent.com
`

**Comment by bin456789** [comment]
？？？
脚本本来就有国内代理
curl -sL http://dash.cloudflare.com/cdn-cgi/trace  | grep loc
查看被 cf 识别成哪国 ip

**Comment by xkatld** [comment]
挂了个梯子没注意...
