### ISSUE TITLE
大佬DD WIN怎么跳过需进入Alpine重启

### ISSUE THREAD

**Issue by jaxMineKa** [bin456789/reinstall#115]
`bash reinstall.sh dd --img=''`
我用这个命令dd windows系统，发现需要ssh 连接重启之后才算完成，请问怎么跳过这个手动重启。

**Comment by bin456789** [comment]
你是说 dd 完成后要手动重启？
有没有报错？截图？

**Comment by jaxMineKa** [comment]
![screen](https://github.com/bin456789/reinstall/assets/153351521/6eb366a1-32c1-401f-b54a-d8c27a35acde)
你这么一说，我重新dd一台，进入看日志确实有报错提示，应该是中断了，这时计算机资源占用几乎为0，重启之后cpu高占用大概五分钟就dd好了，新的windows系统我手动重启和修改密码都没问题。

是gcp，包是nat.ee的

**Comment by jaxMineKa** [comment]
或者包用错了？我没用带efi标识的包

**Comment by jaxMineKa** [comment]
> 或者包用错了？我没用带efi标识的包

使用efi包没这个问题了

**Comment by bin456789** [comment]
噢原来 gcp 可以使用非efi镜像
不过多数 efi 机器无法使用非efi 镜像，如果跳过这个报错，自动重启就失联了
所以 gcp dd 非efi 镜像还是手动重启吧

**Comment by jaxMineKa** [comment]
> 噢原来 gcp 可以使用非efi镜像 不过多数 efi 机器无法使用非efi 镜像，如果跳过这个报错，自动重启就失联了 所以 gcp dd 非efi 镜像还是手动重启吧

不太了解，以前我用非efi包直接dd可以的，好象是萌咖的脚本，就是要手动配置一下ip麻烦。你的其实也是可以，不知道引起这个报错是不是脚本主动性检查的？手动重启后重装也没问题。

**Comment by bin456789** [comment]
> 不知道引起这个报错是不是脚本主动性检查的？

这个脚本运行出错时会中断并显示错误行
之前没想到有人会用普通镜像 dd efi 机器
因此会报错，像图上那样
现在添加了提示告诉用户没有 efi 分区可能无法启动
