### ISSUE TITLE
CentOS Stream 8没有出现

### ISSUE THREAD

**Issue by m4d3bug** [bin456789/reinstall#116]
您好，想问一下，想知道一下没有CentOS Stream 8的原因是？如果自己指定link或者是dd是否奏效？

**Comment by bin456789** [comment]
https://endoflife.date/centos-stream
不支持官方停止维护了的系统

但应该可以用安装红帽的命令安装，指定  centos stream 8 的 qcow2 文件

**Comment by m4d3bug** [comment]
好的，谢谢
