### ISSUE TITLE
请问这个脚本只支持虚拟机吗？

### ISSUE THREAD

**Issue by hausen1012** [bin456789/reinstall#118]
由于物理机环境混乱，想重装系统，但是u盘安装太麻烦，通过这个脚本安装似乎不行。系统是centos7

**Comment by bin456789** [comment]
安装centos7用的是官方打包好的镜像，是给虚拟机用的，镜像内没有固件和微码
脚本也没有添加上，所以用不了

**Comment by hausen1012** [comment]
所以我想确定下，物理机是否能dd呢？

**Comment by bin456789** [comment]
> 大佬，不好意思，我没说清楚。我的物理机系统是centos7，想要dd的系统是debian，执行脚本提示没问题，但是重启并没有进入安装debian的引导界面

这就奇怪了，因为安装debian用的是官方netboot，按道理能用于物理机
就算装不了，至少也能进安装界面
你是重启后进入了哪个界面？

**Comment by hausen1012** [comment]
重启后还是进入之前centos的界面，但是我使用虚拟机centos的话就有reinstall 界面

**Comment by hausen1012** [comment]
> > 大佬，不好意思，我没说清楚。我的物理机系统是centos7，想要dd的系统是debian，执行脚本提示没问题，但是重启并没有进入安装debian的引导界面
> 
> 这就奇怪了，因为安装debian用的是官方netboot，按道理能用于物理机 就算装不了，至少也能进安装界面 你是重启后进入了哪个界面？

刚刚试了下ubuntu22.04，重装20.04发现重启后也是直接进入原来的系统。
![image](https://github.com/user-attachments/assets/c8728307-2bc4-423a-972f-87ff40a5a1d8)

**Comment by bin456789** [comment]
能进bios的话手动选择reinstall.efi引导
不能的话看看以下命令
mount | grep /boot/efi
efibootmgr -v
lsblk -f -o +UUID,PARTUUID

**Comment by bin456789** [comment]
好像没什么问题，再看看
yum install -y mokutil
mokutil --sb-state

**Comment by hausen1012** [comment]
对了大佬，centos不行，我重装了ubuntu，所以现在是ubuntu，发现也是不行。
![image](https://github.com/user-attachments/assets/24ba3652-9893-4958-9b1c-00e5475d0b45)

**Comment by bin456789** [comment]
再看看 tree /boot/efi

**Comment by hausen1012** [comment]
> 再看看 tree /boot/efi

![image](https://github.com/user-attachments/assets/05f9febf-f5ba-46b5-ac10-e28054d45acb)

**Comment by bin456789** [comment]
所有东西都正常
剩下一种可能就是你的电脑不支持设置一次性 efi 引导
但你的电脑是华硕笔记本？大厂应该不会有这种 bug

只能换个脚本试试了，其他脚本用的是添加 grub 引导项，应该没有这种问题

**Comment by hausen1012** [comment]
> 所有东西都正常 剩下一种可能就是你的电脑不支持设置一次性 efi 引导 但你的电脑是华硕笔记本？大厂应该不会有这种 bug
> 
> 只能换个脚本试试了，其他脚本用的是添加 grub 引导项，应该没有这种问题

也有可能是这个bug，这个是很多年之前的机器

**Comment by hausen1012** [comment]
> 所有东西都正常 剩下一种可能就是你的电脑不支持设置一次性 efi 引导 但你的电脑是华硕笔记本？大厂应该不会有这种 bug
> 
> 只能换个脚本试试了，其他脚本用的是添加 grub 引导项，应该没有这种问题

刚看了眼似乎确实是只有boot才能看见引导，但是插上网线好像获取不到网络。
![b9a07e52f90c65298a92e28d83738ac](https://github.com/user-attachments/assets/bdf0dadd-9144-419a-8b20-c786266ba2d4)

**Comment by bin456789** [comment]
alpine netboot 没有你的网卡驱动
试下安装 debian

**Comment by hausen1012** [comment]
> netboot

这是尝试安装ubuntu，ubuntu的也没有吗

**Comment by bin456789** [comment]
这个脚本安装所有系统都会经过alpine（除了安装debian）
所以不支持原生 ubuntu netboot

**Comment by hausen1012** [comment]
> 这个脚本安装所有系统都会经过alpine（除了安装debian） 所以不支持原生 ubuntu netboot
好像之前的会有影响
![image](https://github.com/user-attachments/assets/364c10d2-f3fa-4f34-90f3-d03f1769f632)

**Comment by bin456789** [comment]
efibootmgr
efibootmgr | grep 'reinstall' | awk -F '*' '{print $1}' | sed 's/Boot//'
efibootmgr --quiet --bootnum 0004 --delete-bootnum

**Comment by hausen1012** [comment]
网络环境不行，好像有个文件下载不到。我多试几次看看呢。

还有一个想请教大佬的问题。比如说现在我有一个系统，但是我想把这个系统做为镜像，让其他机器能安装镜像就和现在这个系统一模一样，这种方式能行吗？如果可行的需要怎么做？

我目前的想法是，挂载硬盘，用 dd 命令把整块硬盘写入挂载的硬盘这种方式，不知道是否可行？

如果有方法能把当前的系统做成一个镜像，然后使用大佬您的脚本直接安装就好了。

**Comment by bin456789** [comment]
即使你做了镜像，这个脚本也是用不了的
因为这个脚本dd是在alpine netboot环境下进行的，里面没有你的网卡驱动

不过你可以在本机上直接dd镜像，不用脚本，大概这样
```
echo u >/proc/sysrq-trigger
curl xxx | xz(gzip) -dc | dd of=/dev/sda
echo b >/proc/sysrq-trigger
```

**Comment by hausen1012** [comment]
> 即使你做了镜像，这个脚本也是用不了的 因为这个脚本dd是在alpine netboot环境下进行的，里面没有你的网卡驱动
> 
> 不过你可以在本机上直接dd镜像，不用脚本，大概这样
> 
> ```
> echo u >/proc/sysrq-trigger
> curl xxx | xz(gzip) -dc | dd of=/dev/sda
> echo b >/proc/sysrq-trigger
> ```

请问这个xxx可以是官方提供的好iso镜像吗？还是哪里来？

**Comment by bin456789** [comment]
就是你自己做的镜像啊，大概这样弄
```
dd if=/dev/sda | gzip >/其他硬盘目录/a.gzip
```
不能iso

**Comment by bin456789** [comment]
ubuntu 也有官方镜像，不过是虚拟机用的，你机器用了大概是启动不了
```
echo u >/proc/sysrq-trigger 
curl -L https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.tar.gz | tar xz --wildcards *.img -O >/dev/sda
echo b >/proc/sysrq-trigger
```

**Comment by hausen1012** [comment]
> 就是你自己做的镜像啊，大概这样弄
> 
> ```
> dd if=/dev/sda | gzip >/其他硬盘目录/a.gzip
> ```
> 
> 不能iso

想试试自己做的，那这个是不是必须得准备一块比系统大的硬盘

**Comment by bin456789** [comment]
>想试试自己做的，那这个是不是必须得准备一块比系统大的硬盘

额
备份的话，通常用gzip/xz压缩，所以不用多大
还原的话，是，但假如你先缩小了系统分区再备份的话，就没有这个问题

其实是很简单的东西，网上应该有教程

**Comment by hausen1012** [comment]
> > 想试试自己做的，那这个是不是必须得准备一块比系统大的硬盘
> 
> 额 备份的话，通常用gzip/xz压缩，所以不用多大 还原的话，是，但假如你先缩小了系统分区再备份的话，就没有这个问题
> 
> 其实是很简单的东西，网上应该有教程

其实是上网搜了，但是可能由于对着方面只是匮乏，缺少有效关键词，感谢大佬的解答

**Comment by bin456789** [comment]
你应该搜索 `dd 备份还原系统`，而不是`制作dd镜像`，虽然他们是一回事
会了然后搜索`缩小 ext4`

**Comment by hausen1012** [comment]
大佬，我试了这个，发现备份完，无论是删除还是新增文件，都没有复原。

```sh
dd if=/dev/sda  bs=16384 count=65536 | gzip > /mnt/ubuntu.gzip
# 其他操作 新增删除 xxx
gunzip -c /mnt/ubuntu.gzip | dd of=/dev/sda bs=16384
```

**Comment by bin456789** [comment]
不要乱设置 bs 和 count
备份时要umount sda或者设为只读
还原后再mount

**Comment by hausen1012** [comment]
> 不要乱设置 bs 和 count 备份时要umount sda或者设为只读 还原后再mount

那我sda就是系统盘呢？是不是需要U盘进入系统才能备份？

**Comment by bin456789** [comment]
最好是
但也可以不用，搜索 sysrq-trigger

**Comment by hausen1012** [comment]
感谢耐心解答！！

**Comment by beck-8** [comment]
```bash
root@hostname:/tmp# efibootmgr -v
BootNext: 0004
BootCurrent: 0000
BootOrder: 0001,0000
Boot0000* ubuntu        HD(1,GPT,c89f7608-7019-4c5b-80ff-f1ca30302a40,0x800,0x100000)/File(\EFI\ubuntu\shimx64.efi)
Boot0001  Embedded NIC 1 Port 1 Partition 1     VenHw(3a191845-5f86-4e78-8fce-c4cff59f9daa)
Boot0002* Hard drive C: VenHw(d6c0639f-c705-4eb9-aa4f-5802d8823de6)............................F.........................................................A.....................P.E.R.C. .H.3.4.5. . .F.r.o.n.t. . .(.b.u.s. .0.1. .d.e.v. .0.0.)...
Boot0003* BRCM MBA Slot E100 v21.6.0    BBS(128,BRCM MBA Slot E100 v21.6.0,0x0)................f...........K.........................................................A.....................B.R.C.M. .M.B.A. .S.l.o.t. .E.1.0.0. .v.2.1...6...0...
Boot0004* reinstall (ubuntu 24.04)      HD(1,GPT,c89f7608-7019-4c5b-80ff-f1ca30302a40,0x800,0x100000)/File(\EFI\reinstall\grubx64.efi)
```

不知道为啥，重启之后这个也进不去引导，然后就又进系统了
IDC的物理机
