### ISSUE TITLE
这里的 123@@@ 能不能改成加密文本，而不是用明文

### ISSUE THREAD

**Issue by ezrawic4j** [bin456789/reinstall#12]
https://github.com/bin456789/reinstall/blob/51a630f1b9c33c24f5ee747fb28829561d7b820b/debian.cfg#L24

既然大佬不准备支持自定义密码，我想fork一份然后改一个密码自用，debian.cfg里面的123@@@能不能加密，比如通过md5加密123@@@ 

我只要在cfg里面把123@@@改成md5加密后的文本

实际登录的时候我还是输入123@@@  而别人在代码中看到的只是一串无规则密码 ，无法知道我实际真实的密码

**Comment by bin456789** [comment]
openssl passwd -6 -salt afasf 123@@@
-salt 参数随便填
得到
$6$afasf$IOt4dXxfjwjomFEJzehM4nRF6qe3EUgNTKfmAsG9.E7lVBXZZ6Em8ttgLG7b8NlCKzj1omYkkdjDraF4RPe3v.


删除 d-i passwd/root-password password 123@@@
换成 d-i passwd/root-password-crypted password  上面生成的密文

**Comment by ezrawic4j** [comment]
根据大佬的操作，重新dd了之后，发现输入 afasf 123@@@ 提示密码错误。

必须输入下面哪个长的才可以登录ssh，哪里不对呢 😅

**Comment by bin456789** [comment]
不知道，其实我也没有试过。。。

**Comment by ezrawic4j** [comment]
哈哈哈 你是不是问gpt的 😄
