### ISSUE TITLE
腾讯云轻量云北京 重装debian失败，报错信息：

### ISSUE THREAD

**Issue by Spark100k** [bin456789/reinstall#120]
腾讯云轻量云北京 重装debian失败，报错信息：
![20240721-161722](https://github.com/user-attachments/assets/2b3b9d77-8936-4b6c-8970-aeca8b087030)
![20240721-162340](https://github.com/user-attachments/assets/6e7f20b6-ccb6-4c3b-9f67-efd4cc9fb002)

从win重装debian12 、从win DD镜像重装debian12.6 
从debian12重装debian12、 从debian12 DD重装debian12.6、都失败了，都报错了。
 硬盘格式MBR分区表。
 请帮忙在有空的时候看看，谢谢

**Comment by bin456789** [comment]
好像是 ustc 源有问题
https://mirrors.ustc.edu.cn/debian/pool/main/b/base-files/base-files_12.4%2Bdeb12u6_amd64.deb
429 Too Many Requests
openresty

**Comment by bin456789** [comment]
正常了
https://github.com/ustclug/discussions/issues/465
