### ISSUE TITLE
【反馈】DD重装debian12卡住

### ISSUE THREAD

**Issue by scarlett518** [bin456789/reinstall#121]
重装卡住后进入VNC查看`接收预配置文件失败`，如图所示
![image.png](https://image.dooo.ng/c/2024/07/22/669de25f38c01.webp)
![image.png](https://image.dooo.ng/c/2024/07/22/669de2853e9fb.webp)
这个地址pc端访问需要登陆账号，是不是不支持匿名访问
`https://jihulab.com/bin456789/reinstall/-/raw/main/debian.cf`
机器是国内机，v4禁海外，之前使用脚本重装ubuntu 22.04没有问题

**Comment by bin456789** [comment]
https://jihulab.com/bin456789/reinstall/-/raw/main/debian.cfg
页面没问题
你按alt＋→ 可以进入终端，可以看下网络是否正常

**Comment by bin456789** [comment]
https://www.itdog.cn/ping/jihulab.com
这个域名解析的地址都是国内IP
你的机器应该能正常访问

**Comment by scarlett518** [comment]
> https://jihulab.com/bin456789/reinstall/-/raw/main/debian.cfg 页面没问题 你按alt＋→ 可以进入终端，可以看下网络是否正常
> https://www.itdog.cn/ping/jihulab.com 这个域名解析的地址都是国内IP 你的机器应该能正常访问
感谢，那个地址没有问题，我识别链接的时候最后面少了个g导致链接不完整
alt＋→ 可以进入终端后ping 是没问题的，但是没有办法自动运行，重新DD也是这个问题，我是否按照上面的流程从`下载debconf预配置文件`的下面选项按顺序手动执行
![image.png](https://image.dooo.ng/c/2024/07/22/669dea51a323f.webp)
![image.png](https://image.dooo.ng/c/2024/07/22/669dea6de2932.webp)

**Comment by bin456789** [comment]
你上面的图 ping baidu.com 不通
看下 /etc/resolv.conf 有没有东西

**Comment by scarlett518** [comment]
> 你上面的图 ping baidu.com 不通 看下 /etc/resolv.conf 有没有东西

有的，阿里的DNS
![image.png](https://image.dooo.ng/c/2024/07/22/669dec04ad5a5.webp)

**Comment by bin456789** [comment]
emmm 这题太难，我分析不出结果来

**Comment by scarlett518** [comment]
> emmm 这题太难，我分析不出结果来
没事，还是谢谢大佬了，这家机器v4限制太多了，但v6不限制，我试试能不能添加v6的DNS从v6下载，大佬脚本很好用，对国内也很友好，给大佬点赞，辛苦大佬了

**Comment by scarlett518** [comment]
v6的DNS添加后可以继续了，谢谢大佬
