### ISSUE TITLE
阿里云ECS无法完成安装

### ISSUE THREAD

**Issue by zhonghuhe** [bin456789/reinstall#123]
大陆服务器加剧屏蔽GitHub和https://dl-cdn.alpinelinux.org，导致每次重装都失败。
请问可以做一个大陆可以轻松重装的方式嘛

**Comment by bin456789** [comment]
正常情况国内机器自动会用国内的镜像
你旧系统是不是开了代理？
```
curl -sL http://dash.cloudflare.com/cdn-cgi/trace  | grep loc
```

**Comment by zhonghuhe** [comment]
阿里云上海地区Ubuntu 22.04 64位，默认貌似没有代理，

**Comment by zhonghuhe** [comment]
非常感谢，速度提升了100倍

**Comment by zhonghuhe** [comment]
log=SG会变得非常慢，而且会失败
log=CN快了非常多
请问如何解决，谢谢

**Comment by zhonghuhe** [comment]
loc=SG会变得非常慢，而且会失败
loc=CN快了非常多
请问如何解决，谢谢

**Comment by bin456789** [comment]
？？为什么又sg又cn？
应该是不变的啊

**Comment by zhonghuhe** [comment]
俩台同地区的服务器。

**Comment by bin456789** [comment]
没有用代理的话，就是 cf 的 ip 库有问题了

目前你可以修改脚本
https://github.com/bin456789/reinstall/blob/048ee61ecc8c58e848de37c5286bbe5686b296e4/reinstall.sh#L106-L114

SG 那台改为 loc=SG

**Comment by zhonghuhe** [comment]
非常有效
