### ISSUE TITLE
自动应答文件

### ISSUE THREAD

**Issue by FynnFbc** [bin456789/reinstall#124]
镜像中有自动应答文件，能否选择不用脚本的应答文件

**Comment by bin456789** [comment]
进入win界面马上按ctrl+c中断安装脚本，再运行
```
del x:\autounattend.xml
ren x:\setup.exe.disabled setup.exe
x:\setup.exe
```

不过安装后依然会自动设置 IP
还有分区时不能删除 installer 分区

**Comment by FynnFbc** [comment]
能在重启前就设置就好了，这样操作好麻烦

**Comment by bin456789** [comment]
你也可以修改脚本
https://github.com/bin456789/reinstall#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E8%84%9A%E6%9C%AC

移除不想要的应答文件内容
