### ISSUE TITLE
不支持 KVM (甲骨文云)

### ISSUE THREAD

**Issue by XchenYa** [bin456789/reinstall#125]
重启后连不上才看到这个😭，吸取教训了不看完文档就操作
![image](https://github.com/user-attachments/assets/1b46e2ec-81e3-4ecc-a5fc-0060fd841626)

**Comment by bin456789** [comment]
甲骨文又死不了，随便救砖

**Comment by XchenYa** [comment]
这个倒是没事，删掉重建还更快😁，本来就是打算拿来重装系统的
