### ISSUE TITLE
Linode下使用出现Error: Disk ID is invalid:

### ISSUE THREAD

**Issue by XiChenBaBa** [bin456789/reinstall#129]
![QQ截图20240805224106](https://github.com/user-attachments/assets/c2532873-11eb-48c7-a4d5-299be89f59eb)

**Comment by bin456789** [comment]
看下  fdisk -l /dev/sda 的结果

**Comment by bin456789** [comment]
可能分区表有问题
试下先修复分区表
parted /dev/sda

**Comment by XiChenBaBa** [comment]
![image](https://github.com/user-attachments/assets/261b4a66-013a-49d7-a80a-fd55d79c159e)
大佬能否详细说下怎么修复分区表

**Comment by bin456789** [comment]
输入 p 回车，应该会提醒你修复

**Comment by XiChenBaBa** [comment]
![image](https://github.com/user-attachments/assets/3906bf10-60c4-4b76-872e-07ad88994265)

**Comment by bin456789** [comment]
这硬盘没有分区表，直接将整个硬盘当 ext4 用了，属实是令人窒息的操作
此脚本不支持这种情况，用其他人的脚本吧

**Comment by XiChenBaBa** [comment]
麻烦大佬了
Linode用一些奇银巧技DD成功了
参考的https://ethanblog.com/tips/dd-windows-for-linode-vps.html
在救援模式里直接弄的
