### ISSUE TITLE
请问怎么支持ubuntu桌面版，平台：甲骨文vps arm

### ISSUE THREAD

**Issue by geilige** [bin456789/reinstall#130]
请问怎么支持ubuntu桌面版，平台：甲骨文vps arm

**Comment by bin456789** [comment]
chatgpt 帮到你

**Comment by bin456789** [comment]
脚本没有这个功能，不过这两个软件可以引导iso
https://packages.debian.org/bookworm/grub-imageboot
https://packages.debian.org/bookworm/grml-rescueboot

**Comment by bin456789** [comment]
用netboot.xyz也可以启动ubuntu桌面版

**Comment by geilige** [comment]
真的感谢大佬耐心解答，netboot.xyz我试过，安装的是服务器版；https://packages.debian.org/bookworm/grub-imageboot
https://packages.debian.org/bookworm/grml-rescueboot这两个后面尝试下吧 感谢

**Comment by bin456789** [comment]
我查了下，ubuntu 没有发布官方的 desktop arm iso

**Comment by zhonghuhe** [comment]
> 我查了下，ubuntu没有发布官方的桌面arm iso

#!/bin/bash

# 更新软件包列表
apt-get update

# 升级已安装的软件包
apt-get upgrade -y

# 添加新用户
adduser user

# 安装所需的软件包
apt-get install -y ubuntu-desktop linux-generic linux-firmware xserver-xorg-video-intel

# 再检查一边安装所需的软件包
apt-get install -y ubuntu-desktop linux-generic linux-firmware xserver-xorg-video-intel
这个方式可以安装桌面，此方法在amd可以用，arm未知
