### ISSUE TITLE
是否可以支持重装成hiveOS

### ISSUE THREAD

**Issue by HarryGoFree** [bin456789/reinstall#133]

**Comment by bin456789** [comment]
挖矿专用系统，好家伙，长见识了
但是太小众，不打算支持

我看了下官网的安装教程，是用dd镜像安装的，那可以用脚本dd
```
bash reinstall.sh dd --img https://download.hiveos.farm/latest/
```
重启后，dd过程会报错
因为镜像有ntfs分区，脚本以为是windows镜像，配置 windows ip失败，不过不用管

ssh 连接服务器，挂载第一个分区
```
mount /dev/vda1 /mnt
```
设置 /mnt/rig.conf
如果是静态ip，再设置 /mnt/network/20-ethernet.network
https://hiveon.com/knowledge-base/guides/ip/
完成后reboot重启就行了

**Comment by HarryGoFree** [comment]
感谢大神分享
