### ISSUE TITLE
有没有考虑对大陆网络优化

### ISSUE THREAD

**Issue by a8dog** [bin456789/reinstall#135]
大陆网络脚本全自动化还没有到下载镜像 就失败了

dd功能又只支持xz gzip 比如阿里云的ios镜像就用不了。

**Comment by bin456789** [comment]
已经对大陆网络优化了
还有 dd iso 作用是什么？确实有需要的话可以进 alpine 救援模式手动 dd iso

**Comment by bin456789** [comment]
应该是同一个问题，现在正常了
https://github.com/bin456789/reinstall/issues/136
