### ISSUE TITLE
源系统win11失败

### ISSUE THREAD

**Issue by flt6** [bin456789/reinstall#138]
重启后进入grub命令行界面

**Comment by flt6** [comment]
安全启动已经关闭

**Comment by flt6** [comment]
运行脚本时提示的是hd0,gpt3 但grub里说hd0,gpt3是unknown filesystem

**Comment by bin456789** [comment]
在 grub 下输入下面命令。看下能不能看到c盘的文件
```
 ls (hd0,gpt1)
 ls (hd0,gpt1)/
 ls (hd0,gpt2)
 ls (hd0,gpt2)/
 ls (hd0,gpt3)
 ls (hd0,gpt3)/
```

**Comment by flt6** [comment]
不能看到，但是WinRE在(hd0,gpt4)，windows11的boot分区在(hd0,gpt1)

**Comment by flt6** [comment]
从分区大小可以看到C盘就是(hd0,gpt3)

**Comment by bin456789** [comment]
可能加密了？

**Comment by flt6** [comment]
确定bitlocker已经关闭（刚买就关了）

**Comment by flt6** [comment]
ATI备份数据正常，可以查看

**Comment by bin456789** [comment]
那就奇怪了
只能试下把  c:\cygin\install-vmlinuz c:\cygin\reinstall-initrd 放到 efi 分区和boot分区
再改下 efi 分区下的 grub.cfg
删除所有 /cygwin

**Comment by flt6** [comment]
cfg文件被自动放入C盘了，但是C盘不可读。

**Comment by flt6** [comment]
U启动重装了，故障无法复现，关了吧。
