### ISSUE TITLE
脚本使用的时候怎么指定镜像是自己的镜像，镜像有格式要求吗，我这边要dd成centos8发现现在没有了

### ISSUE THREAD

**Issue by ATanZheng** [bin456789/reinstall#141]

**Comment by bin456789** [comment]
```
bash reinstall.sh alma 8
```
最后会显示 grub.cfg 或者custom.cfg 的路径，编辑文件修改 qcow2 链接为 centos8 的
正常重启

**Comment by ATanZheng** [comment]
大佬如果我想安装自定义的iso镜像呢？
也是这个方法吗？

**Comment by ATanZheng** [comment]
比如我要安装TencentOS Server3.1系统

**Comment by ATanZheng** [comment]
还有就是如果我123网盘中存储的qcow2镜像可以指定链接吗

**Comment by bin456789** [comment]
> 大佬如果我想安装自定义的iso镜像呢？ 也是这个方法吗？
> 比如我要安装TencentOS Server3.1系统

不支持安装 iso





> 还有就是如果我123网盘中存储的qcow2镜像可以指定链接吗

网盘应该不行

**Comment by ATanZheng** [comment]
> > 大佬如果我想安装自定义的iso镜像呢？ 也是这个方法吗？
> > 比如我要安装TencentOS Server3.1系统
> 
> 不支持安装 iso
> 
> > 还有就是如果我123网盘中存储的qcow2镜像可以指定链接吗
> 
> 网盘应该不行

好的，感谢大佬

**Comment by ATanZheng** [comment]
> ```
> bash reinstall.sh alma 8
> ```
> 
> 最后会显示 grub.cfg 或者custom.cfg 的路径，编辑文件修改 qcow2 链接为 centos8 的 正常重启

我使用魔方云的centos8的qcow2镜像发现重装还是报错，不能够通过指定qcow2镜像来实现重装centos系统

**Comment by ATanZheng** [comment]
修改custom.cfg 的qcow2路径修改后，重启安装卡在/etc/default/grub格式错误

**Comment by bin456789** [comment]
已修复

**Comment by ATanZheng** [comment]
收到，其他centos镜像也是这样操作对吧

**Comment by bin456789** [comment]
> 收到，其他centos镜像也是这样操作对吧

刚好魔方云的centos8的qcow2用了阿里云软件源，而阿里云还没有删除centos8的软件源，所以碰巧能用
其他镜像就知道了

**Comment by ATanZheng** [comment]
大佬，dd功能使用自定义镜像重装系统，由于是网络上的镜像导致机器密码无法确认，这个有办法解决吗，在执行脚本的时候设置root密码

**Comment by ATanZheng** [comment]
大佬脚本可以添加一个重装TencentOS系统的功能吗

**Comment by bin456789** [comment]
> 大佬，dd功能使用自定义镜像重装系统，由于是网络上的镜像导致机器密码无法确认，这个有办法解决吗，在执行脚本的时候设置root密码

可以添加 `--hold 2` 参数，连接 ssh，在dd完成后 chroot 修改密码
但镜像有cloud-init的话，密码可能会被cloud-init重置


> 大佬脚本可以添加一个重装TencentOS系统的功能吗


短期内不会支持 https://github.com/bin456789/reinstall/issues/143
