### ISSUE TITLE
你好，移动云电脑公众版无法DD，执行到安装完成cygwin,重启的时候出问题，在命令界面执行shutdown /r /t 0 无法完成重启，机器不重启，云电脑客户端断开连接，开始我以为它正在执行DD，几个小时后机器依然无法连接，用云电脑客户端重启机器，还是原来系统，cygwin还在，重试了几次，换了不同镜像。依然无法解决。似乎是移动云电脑公众版限制了热重启，在原来云电脑系统里面电源按钮的关机，重启和注销功能被砍掉了，执行命令也无法重启。只能从外部重启。请问这个问题怎么解决？谢谢！

### ISSUE THREAD

**Issue by imlzc** [bin456789/reinstall#142]
原来的系统：移动云电脑公众版-win10企业版
要安装的系统：win10,win11
遇到的问题：截图或者登录 SSH 获取日志 /reinstall.log

Original system:
System to be installed:
Issues encountered: Screenshot or log in via SSH to get the logs from /reinstall.log

**Comment by imlzc** [comment]
如果需要云电脑公众版测试该问题，我可以提供

**Comment by bin456789** [comment]
账号密码发我邮箱 bin456789@gmail.com
我测试下

**Comment by laris** [comment]
标题改一下吧，看着太别扭了
CMCC云电脑我晚上刚重装成ubuntu没问题

**Comment by ice-seal** [comment]
我也遇到了你这问题，你解决了吗？

**Comment by ice-seal** [comment]
已解决，找卖家，让他帮你切最新的vnc系统，长时间不链接会自动关机的那个，不要使用不会自动关机的版本即可

**Comment by imlzc** [comment]
> 已解决，找卖家，让他帮你切最新的vnc系统，长时间不链接会自动关机的那个，不要使用不会自动关机的版本即可

谢谢告知，我是自己开通的，你知道怎么切vnc吗

**Comment by ice-seal** [comment]
> > 已解决，找卖家，让他帮你切最新的vnc系统，长时间不链接会自动关机的那个，不要使用不会自动关机的版本即可
> 
> 谢谢告知，我是自己开通的，你知道怎么切VNC吗

目前移动云电脑有两个VNC，具体判断方法
第一种方法：重启，能看到重启过程的就是H3C，看不到重启过程，点击重启就断开链接的是vmtool
第二种方法：在C:\Program Files (x86)目录下看有H3C文件夹还是有vmtool文件夹
![H3C](https://raw.githubusercontent.com/ice-seal/imgs/main/H3C.png)
![vmtool](https://github.com/ice-seal/imgs/raw/main/vmtool.png)
第三种方法：点击重装,vmtool重装10秒左右就重装完成，H3C重装跟你重装你电脑一样的时间


目前我遇到的是vmtool无法DD，H3C才可以，并且同配置下，vmtool的机子要比H3C的卡很多，我vmtool的机子是闲鱼买的，找卖家问了一声，卖家说开机是可以选择系统区域的，有两个系统，一个是不会自动关机的vmtool，一个是长时间没登录会自动关机的H3C，我捣鼓了很久vmtool都无法DD成功，感觉这个控制系统的机子是vm的虚拟机，重装就是恢复快照，你要是vmtool的话，可以找客服叫他帮你切换一下H3C的试试

**Comment by imlzc** [comment]
好的，谢谢

**Comment by Halecoder** [comment]
> 已解决，找卖家，让他帮你切最新的vnc系统，长时间不链接会自动关机的那个，不要使用不会自动关机的版本即可

如果不能切换，是不是凉了，我手上有一台，DD后开机回原系统快照

**Comment by Rainnnray** [comment]
> > > 已解决，找卖家，让他帮你切最新的vnc系统，长时间不链接会自动关机的那个，不要使用不会自动关机的版本即可
> > 
> > 
> > 谢谢告知，我是自己开通的，你知道怎么切VNC吗
> 
> 目前移动云电脑有两个VNC(vmtool和H3C)，具体判断方法 第一种方法：重启，能看到重启过程的就是H3C，看不到重启过程，点击重启就断开链接的是vmtool 第二种方法：在C:\Program Files (x86)目录下看有H3C文件夹还是有vmtool文件夹 ![H3C](https://raw.githubusercontent.com/ice-seal/imgs/main/H3C.png) ![vmtool](https://github.com/ice-seal/imgs/raw/main/vmtool.png) 第三种方法：点击重装,vmtool重装10秒左右就重装完成，H3C重装跟你重装你电脑一样的时间
> 
> 目前我遇到的是vmtool无法DD，H3C才可以，并且同配置下，vmtool的机子要比H3C的卡很多，我vmtool的机子是闲鱼买的，找卖家问了一声，卖家说开机是可以选择系统分组的，有两个系统，一个是不会自动关机的vmtool，一个是长时间没登录会自动关机的H3C，我捣鼓了很久vmtool都无法DD成功，感觉这个控制系统的机子是vm的虚拟机，重装就是恢复快照，你要是vmtool的话，可以找客服叫他帮你切换一下H3C的试试

怎么和客服沟通呢？我跟客服说半天他们不懂，总觉得我是要更改关机策略，扯半天后给我调整为24小时关机，目前我系统C:\Program Files (x86)目录下看是vmtool，没有H3C
