### ISSUE TITLE
能支持一下TencentOS么

### ISSUE THREAD

**Issue by xkatld** [bin456789/reinstall#143]
TencentOS是基于centos78改的有官方源支持，[https://mirrors.tencent.com/tlinux/3.1/isos/x86_64/TencentOS-Server-3.1-20240715.1-TK4-x86_64-everything.iso](url)

**Comment by bin456789** [comment]
目前脚本对类centos系统都是采用解压qcow2云镜像的方法安装
原镜像2g+解压后3g，因此硬盘要求是5g
但是TencentOS镜像解压后是 5g，因此硬盘要求是7g
而脚本的目标是512+5g安装所有linux，因此不能用这种方法

只能用yum安装，这个就以后再说了
