### ISSUE TITLE
应答文件中指定的一个值超出了可接受值的范围

### ISSUE THREAD

**Issue by bailaoshijiadao** [bin456789/reinstall#145]
原来的系统：windows server 2019
要安装的系统：windows 10 pro
遇到的问题：Windows 无法分析或处理 pass [windowsPE]的无人参与应答文件[X:\autounattend,xml]。 应答文件中指定的一个值超出了可接受值的范围。
![微信图片_20240828190428](https://github.com/user-attachments/assets/d0755fc3-cc5d-4e2e-a4d2-91a34f71cea2)

使用iso地址
https://drive.massgrave.dev/zh-cn_windows_10_consumer_editions_version_22h2_updated_aug_2024_x64_dvd_2454bb57.iso

**Comment by bin456789** [comment]
难搞
点确定，输入 notepad x:\autounattend.xml 截图看下 ImageInstall 那部分

**Comment by bailaoshijiadao** [comment]
> ImageInstall

![QQ图片20240828193943](https://github.com/user-attachments/assets/d40a2bbb-8232-41fa-83e2-5a41b09913fa)

**Comment by bin456789** [comment]
再输入 echo list disk | diskpart 看看

**Comment by bin456789** [comment]
还有 echo list vol | diskpart

**Comment by bailaoshijiadao** [comment]
> echo list vol | diskpart

![QQ图片20240828195129](https://github.com/user-attachments/assets/6bd65154-594f-41ac-98a7-f7e476d5449e)

**Comment by bin456789** [comment]
猜测是刚才硬盘状态是 Foreign 导致出问题

目前建议你修改 X:\autounattend,xml，将 DiskID 的 Foreign改为0，再输入 y:\setup 安装系统

**Comment by bailaoshijiadao** [comment]
> 猜测是刚才硬盘状态是 Foreign 导致出问题
> 
> 目前建议你修改 X:\autounattend,xml，将 DiskID 的 Foreign改为0，再输入 y:\setup 安装系统

成功安装了，谢谢

**Comment by bin456789** [comment]
我刚才猜错了
真正的缘由是第二个硬盘是动态磁盘，干扰了脚本的判断（脚本没考虑到这种情况），现在已经修复

**Comment by bailaoshijiadao** [comment]
> 我刚才猜错了 真正的缘由是第二个硬盘是动态磁盘，干扰了脚本的判断（脚本没考虑到这种情况），现在已经修复

脚本可以在安装的时候把windows的两个硬盘合并成一个盘使用吗？

**Comment by bin456789** [comment]
不能
