### ISSUE TITLE
请问功能一【安装Linux】和功能二【DD】有什么区别？

### ISSUE THREAD

**Issue by gabriel254** [bin456789/reinstall#147]
您好，我目前在用腾讯云，想去掉腾讯自带的各种监控。如果我想安装一个纯净的官方Debian12镜像，请问我应该使用README里描述的功能一【安装Linux】还是功能二【DD】呢？

**Comment by bin456789** [comment]
功能1安装的 debian等于iso安装，显然是纯净的
功能2 dd 官方云镜像的话
```
https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.raw
https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.raw 
```
也是官方出品，但是云镜像多了些iso安装没有的软件，例如 netplan，cloud-init
网卡也设置成 eth0 这种名字
看你怎么定义纯净

**Comment by gabriel254** [comment]
感谢解答！
