### ISSUE TITLE
重装修改镜像为iso报错

### ISSUE THREAD

**Issue by zhonghuhe** [bin456789/reinstall#150]
原来的系统：Windows 
要安装的系统：ubuntu24.04
遇到的问题：截图或者登录 SSH 获取日志 /reinstall.log
重装成ubuntu时在重启前修改了镜像成http://releases.ubuntu.com/noble/ubuntu-24.04.1-live-server-amd64.iso
镜像下载完成之后总是报错详情见附图
![fk](https://github.com/user-attachments/assets/51572249-3a27-4f68-98d2-2917e2465528)

**Comment by bin456789** [comment]
不能这样玩的，实在想用iso安装的话，可以这样安装
`reinstall.bat ubuntu --installer`

但是只支持dhcp

**Comment by zhonghuhe** [comment]
![fk](https://github.com/user-attachments/assets/8e2eb314-dfa5-4c37-a7ce-78b604cd1346)
好像还是报错，这个是提示下载失败

**Comment by bin456789** [comment]
登录进去
less /reinstall.log 看下第一个错误是什么

**Comment by zhonghuhe** [comment]
![fk](https://github.com/user-attachments/assets/e6b22df0-3055-44e8-91b5-a1debba184ce)
是我这边配置有问题嘛

**Comment by bin456789** [comment]
没看到错误，下拉找下 Error 再截图吧

**Comment by bin456789** [comment]
我的问题，现在可以了

**Comment by zhonghuhe** [comment]
现在可以了
