### ISSUE TITLE
多谢大佬，但是Oracle arm vm重装失败

### ISSUE THREAD

**Issue by choicky** [bin456789/reinstall#152]
原来的系统：Debian 12
要安装的系统：Debian 12
遇到的问题：重启后等很久都无法 SSH 到服务器，估计是重装失败了。

我在zgo的一台vps上测试过大佬的脚本，能顺利重装Debian 12。

我Oracle arm VM 原来的 Debian 是使用其他人的脚本安装的。因为总觉得有点小毛病，所以想试一下大佬的这个脚本重装一下。

但是，重启Oracle arm vm之后，一直无法ssh连接进去。我用另一台 Oracle AMD vm试了本脚本，重启后能顺利ssh进去。

也就是说，都是 Oracle 的VM，AMD CPU的vm能使用本脚本重装Debian 12，但ARM CPU的vm使用本脚本重装之后，无法ssh进入。

因为Oracle VM没有重装系统的功能，我只好 terminated ，然后打算重开。结果，重开时就一直提示 `Out of capacity for shape VM.Standard.A1.Flex in availability domain AD-1`  ，太郁闷了，没了一台 arm 机器。

**Comment by bin456789** [comment]
1. 甲骨文有 VNC
2. 甲骨文能用 netboot.xyz 救砖

What can I say?
