### ISSUE TITLE
小鸡无限重装

### ISSUE THREAD

**Issue by startuip** [bin456789/reinstall#155]
原来的系统：debian 11
要安装的系统：debian 11
遇到的问题:    小鸡是鸡仔云的，v4 nat鸡，v6独立，amd64架构，运行脚本重装debian11，过程无报错，输入reboot后小鸡进入重装，过了10分钟左右发现ssh连不上，进后台面板打开vnc观察还在重装，继续观察后发现启动项里还有install xxx,的启动项，就这样一直死循环

**Comment by bin456789** [comment]
这样小众机没有报错截图无法排查

而且我感觉我的脚本不会死循环

**Comment by startuip** [comment]
> 这样小众机没有报错截图无法排查
> 
> 而且我感觉我的脚本不会死循环

没报错，就是无限重装，截图也没什么好看的，就是正常重装流程，我看vnc重装完重启又重装

**Comment by bin456789** [comment]
nodeseek上发帖无限重装的是你？

**Comment by startuip** [comment]
> nodeseek上发帖无限重装的是你？

不是我，我也刚刚才刷到这个帖子

**Comment by startuip** [comment]
> > nodeseek上发帖无限重装的是你？
> 
> 不是我，我也刚刚才刷到这个帖子

但是我的情况跟他是一模一样的

**Comment by bin456789** [comment]
那个帖子不是用我的脚本
而且install xxx 也不是我的脚本的条目，我的是 reinstall xxx
除非是原系统的grub有问题，否则我的脚本不会无限循环重装的
