### ISSUE TITLE
希望可以自定义Linux ISO

### ISSUE THREAD

**Issue by SNESNya** [bin456789/reinstall#157]
如题，想要安装Proxmox VE

**Comment by bin456789** [comment]
引导iso需要把iso加载到内存
小鸡不够内存，用不了
独服又有IPMI，用不上
所以脚本没有这个功能

你可以试下这两个软件
https://packages.debian.org/bookworm/grub-imageboot
https://packages.debian.org/bookworm/grml-rescueboot

**Comment by bin456789** [comment]
在 debian 基础上可以安装 pve
netboot.xyz 可以引导 pve iso

**Comment by SNESNya** [comment]
> 在 debian 基础上可以安装 pve netboot.xyz 可以引导 pve iso

求教一下netboot.xyz怎么引导pve 谢谢！

**Comment by bin456789** [comment]
？？？直接菜单选择啊

**Comment by SNESNya** [comment]
> ？？？直接菜单选择啊

没找到在哪里（
麻烦说一下 谢谢大佬了！

**Comment by SNESNya** [comment]
> ？？？直接菜单选择啊

找到了 谢谢大佬
