### ISSUE TITLE
windows 无法运行，脚本能下载下来，但无法运行

### ISSUE THREAD

**Issue by kirito201711** [bin456789/reinstall#159]
Download: http://www.cygwin.com/setup-x86_64.exe C:\Users\ADMINI~1\AppData\Local\Temp\1\setup-cygwin.exe
****  Online  ****
  0000  ...
  00c7
CertUtil: -URLCache command FAILED: 0x80190193 (-2145844845 HTTP_E_STATUS_FORBIDDEN)
CertUtil: Forbidden (403).
The system cannot execute the specified program.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.

**Comment by bin456789** [comment]
目测是阿里云，被cygwin官网拉黑了



把 http://www.cygwin.com/setup-x86_64.exe 下载下来
https://github.com/bin456789/reinstall/blob/76c3ab01a23e8676a6145b89a973eded59c615ec/reinstall.bat#L108
将 `%tmp%\setup-cygwin.exe` 改成硬盘里 setup-x86_64.exe 的路径

**Comment by kirito201711** [comment]
使用你的方法在powershell里面不行，cmd可以了，但是又遇到Download grub下不下来的情况

**Comment by kirito201711** [comment]
ok，成功了，在重启了
