### ISSUE TITLE
arch是否能内置个编辑器

### ISSUE THREAD

**Issue by rwoss** [bin456789/reinstall#16]
发现手上有些机器写入网络配置有点问题 想在vnc里面修改配置 但是连vi都没有 只能通过echo写入

**Comment by bin456789** [comment]
都能进vnc了，手动装一个咯
不是人人喜欢vi，有人喜欢nano，所以保持纯净就好

**Comment by rwoss** [comment]
不是 主要是没网啊 装完之后网卡配置有点问题 要在vnc里面改网卡配置 没编辑器可用

**Comment by bin456789** [comment]
有道理，但我还是想保持系统纯净
你可以在运行脚本时添加 --sleep=2
这样安装后不会重启到 arch
这时可以连接ssh，chroot到/os 安装你要的软件

**Comment by rwoss** [comment]
好的 明白了
