### ISSUE TITLE
甲骨文 AMD dd Debian 重启后卡死

### ISSUE THREAD

**Issue by lyc8503** [bin456789/reinstall#160]
原来的系统：Ubuntu 22.04
要安装的系统：Debian12

重启后卡在如下地方，无任何反应超过十分钟
![image](https://github.com/user-attachments/assets/136db66b-7229-4dfd-bafa-1898dc3d387b)

**Comment by lyc8503** [comment]
尝试了 Debian 12 和 11 均是这个症状... 还尝试了萌咖的 dd 也无法安装 Debian 12. 是 Debian 出什么问题了吗...

**Comment by bin456789** [comment]
安装debian要在vnc查看进度，你这个是控制台

**Comment by lyc8503** [comment]
中午就尝试了 dd，之后吃完饭等了一个小时都没 ping 通和连上 ssh。

刚刚重装后尝试 dd 成 Ubuntu 22.04，没有问题，可以正常启动，那暂时不深究了...
