### ISSUE TITLE
nju 的源在腾讯云北京地域非常慢

### ISSUE THREAD

**Issue by devhaozi** [bin456789/reinstall#161]
原来的系统：ubuntu24.04
要安装的系统：ubuntu24.04

遇到的问题：nju 的源在腾讯云北京地域非常慢，建议换腾讯的源，速度快且不限速。

https://mirrors.tencent.com/ 有些镜像比如alpine没列出来，实际是有的。

**Comment by bin456789** [comment]
更新不够大学源勤快啊
https://mirror.nju.edu.cn/ubuntu-cloud-images/releases/24.04/
https://mirrors.cloud.tencent.com/ubuntu-cloud-images/releases/24.04/

**Comment by devhaozi** [comment]
> ubuntu-cloud-images/releases/24.04/

或者试试清华mirrors.tuna.tsinghua.edu.cn、中科大mirrors.ustc.edu.cn、华为的repo.huaweicloud.com也行。

**Comment by devhaozi** [comment]
> 有趣了，我现在也打不开 nju，估计是挂了

怕不是晚上腾讯云活动，很多人dd给它压垮了。。。

**Comment by bin456789** [comment]
很多镜像源都缺少文件的，我之前也是找过很久，才使用nju的
https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/releases/
https://unicom.mirrors.ustc.edu.cn/ubuntu-cloud-images/releases/
https://mirrors.huaweicloud.com/ubuntu-cloud-images/releases/
https://mirror.nju.edu.cn/ubuntu-cloud-images/releases/
https://mirror.nyist.edu.cn/ubuntu-cloud-images/releases/
https://cloud-images.ubuntu.com/releases/

**Comment by devhaozi** [comment]
搜狐的有测过吗？https://mirrors.sohu.com/ubuntu-cloud-images/releases/

**Comment by devhaozi** [comment]
> 搜狐没ipv6

国内机器应该没有仅ipv6的，脚本可以先ping试试，不行就nju

**Comment by devhaozi** [comment]
大学镜像除了清华和中科大，其他都不太靠谱的样子。

**Comment by bin456789** [comment]
不想搞那么复杂啊，而且说不好别的机器是访问 sohu 快还是 nju 快

你可以先这样
运行脚本最后会显示 grub.cfg 或者 custom.cfg 的路径
重启前修改这个文件里面的镜像网址即可

**Comment by devhaozi** [comment]
ok

**Comment by bin456789** [comment]
> 大学镜像除了清华和中科大，其他都不太靠谱的样子。

其实都有坑，等什么时候遇到 nju 的坑再换掉
https://github.com/tuna/issues/issues/1999
https://github.com/ustclug/discussions/issues/469

**Comment by devhaozi** [comment]
> > 大学镜像除了清华和中科大，其他都不太靠谱的样子。
> 
> 其实都有坑，等什么时候遇到 nju 的坑再换掉 [tuna/issues#1999](https://github.com/tuna/issues/issues/1999) [ustclug/discussions#469](https://github.com/ustclug/discussions/issues/469)

所以我一般还是喜欢用大厂的，可惜几个大厂现在也就腾讯云和华为云不怎么限速了。
网易搜狐的镜像太少了。
