### ISSUE TITLE
如何更改下载重试次数？

### ISSUE THREAD

**Issue by iDtMail** [bin456789/reinstall#163]
下载dd包的时候断开5次就failed了，有什么方法更改次数？

**Comment by bin456789** [comment]
自己改脚本

https://github.com/bin456789/reinstall?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E8%84%9A%E6%9C%AC
https://github.com/bin456789/reinstall/blob/76c3ab01a23e8676a6145b89a973eded59c615ec/trans.sh#L74-L83

将 5 改成其他
