### ISSUE TITLE
安装ubuntu突然报错了

### ISSUE THREAD

**Issue by Jz1028** [bin456789/reinstall#166]
原来的系统：window server 2019
要安装的系统：ubuntu
遇到的问题：以前安装没啥事，昨天突然报错不让安装了，可以登录，但是sudo apt命令都不让用了
<img width="981" alt="image" src="https://github.com/user-attachments/assets/adccf850-09f3-4943-8073-c25f968722bf">

**Comment by bin456789** [comment]
网络/软件源问题，建议重试

**Comment by Jz1028** [comment]
大佬，这个脚本怎么换源？一直失败

**Comment by bin456789** [comment]
在出错后登录进入
编辑 `/etc/apk/repositories` 换源
再输入 `xda=sda /trans.sh `
如果出错运行 `xda=vda /trans.sh `
