### ISSUE TITLE
Password 

### ISSUE THREAD

**Issue by Abiputrapratamaw** [bin456789/reinstall#167]
add the custom Windows password feature bro, via reinstall.sh, not via trans.sh, so it's like --passwin

**Comment by Abiputrapratamaw** [comment]
Because every 10 minutes after installation, the administrator account will be blocked.

**Comment by Abiputrapratamaw** [comment]
oh yeah, one more thing, add auto install + install google chrome for windows

**Comment by bin456789** [comment]
> Because every 10 minutes after installation, the administrator account will be blocked.

This is normal, and interestingly, Azure is the same.
> https://www.bitdefender.com/blog/hotforsecurity/microsoft-blocks-rdp-brute-force-attacks-by-default-in-windows-11
> https://support.microsoft.com/topic/kb5020282-account-lockout-available-for-built-in-local-administrators-bce45c4d-f28d-43ad-b6fe-70156cb2dc00
> https://learn.microsoft.com/troubleshoot/azure/virtual-machines/windows/cannot-rdp-azure-vm-brute-force

Custom password feature will be added. But later.

> oh yeah, one more thing, add auto install + install google chrome for windows

To keep the system clean, Chrome will not be added.

**Comment by Abiputrapratamaw** [comment]
> > Because every 10 minutes after installation, the administrator account will be blocked.
> 
> This is normal, and interestingly, Azure is the same.
> 
> > https://www.bitdefender.com/blog/hotforsecurity/microsoft-blocks-rdp-brute-force-attacks-by-default-in-windows-11
> > https://support.microsoft.com/topic/kb5020282-account-lockout-available-for-built-in-local-administrators-bce45c4d-f28d-43ad-b6fe-70156cb2dc00
> > https://learn.microsoft.com/troubleshoot/azure/virtual-machines/windows/cannot-rdp-azure-vm-brute-force
> 
> Custom password feature will be added. But later.
> 
> > oh yeah, one more thing, add auto install + install google chrome for windows
> 
> To keep the system clean, Chrome will not be added.

Hopefully you will receive your custom password soon

**Comment by bin456789** [comment]
Now supports custom password and custom port
