### ISSUE TITLE
国内机 下载不下来 啥原因呢？ 换了好几个代理了

### ISSUE THREAD

**Issue by ezrawic4j** [bin456789/reinstall#17]
http://ftp.cn.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0curl: (7) Failed connect to ftp.cn.debian.org:80; Operation now in progress
Error: Line 63 return 7
    command curl --connect-timeout 5 --retry 2 --retry-delay 1 -f "$@"

**Comment by ezrawic4j** [comment]
初始系统  不支持CentOS7吗

**Comment by bin456789** [comment]
啥叫换了好几个代理？

**Comment by bin456789** [comment]
据说这个源拉黑了国外ip

**Comment by ezrawic4j** [comment]
如何自定义源？国内vps

**Comment by ezrawic4j** [comment]
如何定义其他源地址呢？比如中科大的

**Comment by ezrawic4j** [comment]
> 啥叫换了好几个代理？

就是用了好几个国内下载GitHub加速的网站和脚本 都不行，就是那种在GitHub网址前面带另外一个网址的那种链接

**Comment by bin456789** [comment]
不能自定义

你直接运行wget http://ftp.cn.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
不行的话就是网段被网站拉黑了

**Comment by ezrawic4j** [comment]
什么时候支持一下自定义源呢？真的很重要！！！！！

**Comment by bin456789** [comment]
永远都不会支持，这辈子都不可能的

**Comment by ezrawic4j** [comment]
> 永远都不会支持，这辈子都不可能的

为啥呢

**Comment by ezrawic4j** [comment]
> 永远都不会支持，这辈子都不可能的

那可以换个源吗 不要用cn.ftp可 换中科大 或者清华源 或者北京外国语学校 或者 其他国内源

**Comment by bin456789** [comment]
不能，写死了

**Comment by bin456789** [comment]
你可以先换个脚本用，安装debian几乎所有脚本都支持

**Comment by bin456789** [comment]
脚本的 debian 国内源已改成清华源
如果要改其他国内源，运行脚本后改 /boot/grub/custom.cfg
