### ISSUE TITLE
格式化为XFS文件系统

### ISSUE THREAD

**Issue by Arxhexa** [bin456789/reinstall#172]
您好，我想在Debian系统中将XFS作为系统分区的文件系统来使用。请问仅在`debian.cfg`配置文件`# B.4.7. 分区`之后添加
`d-i partman/default_filesystem string xfs`
可以达到预期效果吗？

**Comment by bin456789** [comment]
还需要删掉这两行
https://github.com/bin456789/reinstall/blob/b3fef989b0083e37d144a749765329e2ec4a8614/reinstall.sh#L2521
https://github.com/bin456789/reinstall/blob/b3fef989b0083e37d144a749765329e2ec4a8614/reinstall.sh#L2537
