### ISSUE TITLE
reinstall.sh: line 1342: `setos_netboot.xyz': not a valid identifier

### ISSUE THREAD

**Issue by xiaoyi510** [bin456789/reinstall#173]
原来的系统：debian 12 
要安装的系统：debian 12
遇到的问题：截图或者登录 SSH 获取日志 /reinstall.log

[not a valid identifier](reinstall.sh: line 1342: `setos_netboot.xyz': not a valid identifier)

![image](https://github.com/user-attachments/assets/347c2a7e-57b8-40b1-a62c-c6bea747871a)

**Comment by bin456789** [comment]
用 bash
