### ISSUE TITLE
无法在windows server下使用

### ISSUE THREAD

**Issue by ice0625** [bin456789/reinstall#179]
原来的系统：windows server 2022
要安装的系统：debian/windows server
遇到的问题：在有管理员权限的CMD内输入reinstall.bat xxx(debian,windows等等)后均会提示: ←[31Error: Could not detect RAM size.←[0m或Error: Could not detect RAM size.请问如何解决?

**Comment by bin456789** [comment]
找到这一行
https://github.com/bin456789/reinstall/blob/508661d676c552582d238847a194b414bccd3b0d/reinstall.sh#L1709
改成 ram_size=1024 或你的内存大小

**Comment by ice0625** [comment]
修改reinstall.sh 后,传回这个: /cygdrive/c/Users/Administrator/reinstall.sh: line 1709: syntax error near unexpected token `('

**Comment by bin456789** [comment]
我改了点代码
删除 reinstall.sh 重新运行 reinstlal.bat 吧

**Comment by ice0625** [comment]
已删除 reinstall.sh,再运行reinstall.bat提示: /usr/bin/bash: 行 1: /cygdrive/c/Users/Administrator/reinstall.sh: Permission denied

**Comment by bin456789** [comment]
忘记加运行权限
删除 reinstall.bat reinstall.sh 
重新运行就行了

**Comment by ice0625** [comment]
已删除重新再运行,不修改会提示: ***** ERROR *****  Error: Could not detect RAM size., 修改ram_size后会提示: /cygdrive/c/Users/Administrator/reinstall.sh: line 1710: syntax error near unexpected token `('

**Comment by bin456789** [comment]
首页上的下载方法好像有缓存的
在本地下载后再复制到远程服务器试下
