### ISSUE TITLE
windows dd linux 报错

### ISSUE THREAD

**Issue by tangluya** [bin456789/reinstall#18]
机器RDP：
143.244.184.204:3389
administrator
123@@@

我从debian11可以dd到windows11(指定iso)，但是dd到centos7报错
![image](https://img.tanglu.me/2023/10/23/kceuhh.webp)

**Comment by bin456789** [comment]
不能直接复制粘贴的，只能下载文件
或者从远程桌面复制进去

**Comment by tangluya** [comment]
> 不能直接复制粘贴的，只能下载文件 或者从远程桌面复制进去

唉 还真是
为什么不能复制代码粘贴 然后再改文件后缀呀

**Comment by bin456789** [comment]
搜索 windows linux 换行符

**Comment by tangluya** [comment]
> 搜索 windows linux 换行符

哦 感谢
老哥可以加个tg嘛 @tangluya
测试的时候会遇到点问题 想请教下
