### ISSUE TITLE
可以安装第三方镜像吗？

### ISSUE THREAD

**Issue by Jz1028** [bin456789/reinstall#184]
大佬，现在有一个 飞牛OS ，基于debian发行的， 但是他的镜像只有iso的。
假如我把iso转成支持的这种格式 **支持 raw vhd 或者经过 xz gzip 压缩的镜像** ，理论上可以安装成功吗？

**Comment by bin456789** [comment]
理论上和实际上都能安装，网上早就有dd包

**Comment by Jz1028** [comment]
卧槽，我搜了一下还真有，感谢大佬！
