### ISSUE TITLE
找了一圈似乎并没有发现 DD 时能注入密钥

### ISSUE THREAD

**Issue by Anbool** [bin456789/reinstall#185]
我用的 debian-12-genericcloud-amd64.raw 镜像，通过 dd 参数安装的，genericcloud 默认仅密钥登录，怎么办呀大宝贝。

可能我使用方法不对，有没有最佳实践呢？

**Comment by bin456789** [comment]
genericcloud 要用创建机器时的密钥登录
要自己注入密钥用nocloud，加--hold 2参数

**Comment by Anbool** [comment]
> genericcloud 要用创建机器时的密钥登录 要自己注入密钥用nocloud，加--hold 2参数

我直接执行了 ./reinstall.sh debian 好像也没下载镜像就直接装上了 6.1.0-25-cloud-amd64 就比较奇怪，似乎不需要我再准备镜像了。

**Comment by Anbool** [comment]
> 本来就不需要准备镜像 除非使用dd 功能

我爱你，我的朋友。
