### ISSUE TITLE
国内机器dibian to win10, 一直无法下载virtio

### ISSUE THREAD

**Issue by momo-z** [bin456789/reinstall#187]
原来的系统：debian
要安装的系统：win10
遇到的问题：截图或者登录 SSH 获取日志 /reinstall.log

Original system:
System to be installed:
Issues encountered: Screenshot or log in via SSH to get the logs from /reinstall.log
![image](https://github.com/user-attachments/assets/5fdf280d-4390-484b-a24a-90c11a5bf2a6)

**Comment by momo-z** [comment]
再补充一个消息，下载virtio失败后，退到了救援系统，可以查看日志的界面，但是我reboot之后，就再也无法进入系统，一直卡在如下界面
![image](https://github.com/user-attachments/assets/ff6d3ca3-591a-46af-9524-7c4e364d4995)

**Comment by bin456789** [comment]
这个驱动国内没有镜像

唯一的办法是自行修改代码，readme 最下面有教程
改下 virtio-win-gt-x64.msi 链接
https://github.com/bin456789/reinstall/blob/8d1ee541e3d720bf08c9071e199602801d7a2791/trans.sh#L4413

例如
```
download http://xxx.com/virtio-win-gt-x64.msi $drv/virtio.msi
```
