### ISSUE TITLE
腾讯轻量云上海区域 dd失败

### ISSUE THREAD

**Issue by ezrawic4j** [bin456789/reinstall#19]
<img width="1010" alt="image" src="https://github.com/bin456789/reinstall/assets/121549438/a8717098-e962-4cc9-b3a9-f32823f268ae">

**Comment by bin456789** [comment]
出现这个说明已经在安装，不过没显示，等他几分钟就好了

显示问题迟点修复

**Comment by ezrawic4j** [comment]
等了一两个小时了 还是卡在这

**Comment by bin456789** [comment]
运行脚本后删除 /boot/grub/custom.cfg 里面的 console=ttyS0,115200n8
重启
就能看到画面，还有出错内容（如果有）

**Comment by bin456789** [comment]
现已修复
