### ISSUE TITLE
debian12 dd成功后内存显示不对

### ISSUE THREAD

**Issue by f3liiix** [bin456789/reinstall#190]
原来的系统：windows 10 pro
要安装的系统：debian 12
遇到的问题：DD成debian12后，内存只有850M（原始内存为16G），但是debian11正常。

**Comment by bin456789** [comment]
第一次听说这种问题
装个普通版内核试下
apt install linux-image-amd64

然后开机时选择不带cloud的内核

**Comment by f3liiix** [comment]
> 第一次听说这种问题 装个普通版内核试下 apt install linux-image-amd64
> 
> 然后开机时选择不带cloud的内核

是在dd好的debian12里再用apt命令安装普通版内核吗？

**Comment by bin456789** [comment]
是的

**Comment by f3liiix** [comment]
试过了，还是不行，依然显示的850M
![5F3EOY](https://img.hoofei.com/2024/11/5F3EOY.png)

**Comment by bin456789** [comment]
我也不懂
你试下其他人的重装脚本，如果还是一样，就是debian的问题了

**Comment by f3liiix** [comment]
重试了一遍，安装完内核之后重启系统，再用free -m看，好了。
