### ISSUE TITLE
安装过程当中出现dirname问题

### ISSUE THREAD

**Issue by Panda-Goo** [bin456789/reinstall#192]
![image](https://github.com/user-attachments/assets/78a15970-9ac9-4b91-bcdc-dfcde9d703a8)

**Comment by bin456789** [comment]
不是哥们
你觉得这个脚本可以给pi用？

**Comment by Panda-Goo** [comment]
啊？这不能给arm设备用么？

**Comment by bin456789** [comment]
这个脚本支持的arm指的是arm服务器
不过如果你的pi是用uefi引导的，可能也能用

**Comment by Panda-Goo** [comment]
谢谢大佬解答
