### ISSUE TITLE
DDwin突然又用不了了！

### ISSUE THREAD

**Issue by ice-seal** [bin456789/reinstall#196]
原来的系统：Windows Server 2019 ，Debian11
要安装的系统：Windows 10 LTSC
遇到的问题：
![image](https://github.com/user-attachments/assets/ba1777c1-0f1d-45dd-90ff-d3ccb93cf62d)

**Comment by ice-seal** [comment]
100G的硬盘，但是这个报错提示存储空间不足

**Comment by ice-seal** [comment]
https://github.com/bin456789/reinstall/tree/658c73c1a124cd10853cb1bf5c131869316bd651

使用这个版本已解决

**Comment by bin456789** [comment]
不应该啊，发个iso链接研究下？

**Comment by ice-seal** [comment]
> 不应该啊，发个iso链接研究下？

https://pan.mixrnet.com/d/VPS%E5%82%A8%E5%AD%98/%E7%B3%BB%E7%BB%9F%E9%95%9C%E5%83%8F/DD%E9%95%9C%E5%83%8F/Windows10_22H2_19045.4291_X64.iso


不忘初心的精简版，使用https://github.com/bin456789/reinstall/tree/658c73c1a124cd10853cb1bf5c131869316bd651之前的版本都可以安装，其他的精简系统也可以，现在最新的装不了

**Comment by bin456789** [comment]
原版系统用的是 wim 镜像，而这个修改版用的是esd镜像，之前没考虑这一点所以有bug
现在正常了
