### ISSUE TITLE
能否提供dd安装镜像的选项

### ISSUE THREAD

**Issue by arloor** [bin456789/reinstall#2]
这个项目很棒，刚刚用他在腾讯云轻量服务器上安装了centos9-stream。
能否提供一个dd的选项呢？
因为我的服务器比较多，非dd安装的方式要每个机器都通过VNC操作一遍。
如果提供dd的方式，那么只需要通过VNC安装一次，然后制作dd镜像，后续都通过该镜像dd安装，这样会方便很多。
希望大佬支持下！

**Comment by bin456789** [comment]
在小红书真大佬面前，我不敢当
dd应该会搞，因为这个脚本后期可能会添加 cloud image 支持，需要用到 dd，不过这个不是首要任务
目前的话，市面上各种dd脚本，随便一个都符合你要求吧

**Comment by arloor** [comment]
好的，感谢大佬，有计支持就很感激了！
我现在用的是萌咖的dd脚本，他的中间系统是debain，版本太老了，怕某天就GG了。用alpine当中间系统很好！
重装脚本能支持这么多系统应该很耗时，各种发行版的自动安装调试很花时间。
感谢大佬，宝藏项目。

**Comment by arloor** [comment]
大佬的脚本写的太漂亮了，太强了，膜拜！

**Comment by bin456789** [comment]
😂

**Comment by bin456789** [comment]
现在可以dd了
我看了下国内常见的dd镜像，都是gz或者xz压缩
实现dd也就几行代码，就不鸽了

**Comment by arloor** [comment]
> 现在可以dd了 我看了下国内常见的dd镜像，都是gz或者xz压缩 实现dd也就几行代码，就不鸽了

太酷啦大佬！您的就是最强reinstall脚本
