### ISSUE TITLE
国内机2 4 6 dd arch 出现错误

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bin456789/reinstall#20]
mke2fs 1.47.0 (5-Feb-2023)
Creating filesystem with 524032 4k blocks and 131072 inodes
Filesystem UUID: 79eb02fa-5c3d-4d28-a940-b9f9824b8996
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done 

/dev/vda:
 re-reading partition table
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
WARNING: updating and opening http://dl-cdn.alpinelinux.org/alpine/v3.18/community: IO ERROR
ERROR: unable to select packages:
  qemu-img (no such package):
    required by: world[qemu-img]
Error: Line 1093 return 1
    apk add qemu-img lsblk

<img width="983" alt="image" src="https://github.com/bin456789/reinstall/assets/147643826/b694e892-97a7-40c9-b1ef-a5d25146f148">

**Comment by bin456789** [comment]
已修复
