### ISSUE TITLE
您好，希望能把Debian网卡名统一改为经典的eth0方式，像Ubuntu、Rocky、Almalinux一样。

### ISSUE THREAD

**Issue by GiT0WOalVjZ6ZhToNFeqLpdYByfodiQ4nksWmTL** [bin456789/reinstall#205]
原来的系统：Ubuntu、Rocky、Almalinux
要安装的系统：Debian
遇到的问题：截图或者登录 SSH 获取日志 /reinstall.log
![无标题](https://github.com/user-attachments/assets/fb4556da-4d08-4723-912a-6f798e93a7be)

当前的脚本重装为Debian，网卡名是新式的ens加数字，如ens3，而且不同机器也会变化。由于一些应用程序需要调取网卡名，就带来了不便。希望能跟Ubuntu、Rocky、Almalinux一样，将第一网卡统一为经典的eth0方式。

谢谢！

**Comment by bin456789** [comment]
有这种需求可以用云镜像安装
bash reinstall.sh debian --ci

**Comment by GiT0WOalVjZ6ZhToNFeqLpdYByfodiQ4nksWmTL** [comment]
感谢回复！主要是有些时候要在实体机上用，物理机上用云镜象系统感觉怪怪的 。

**Comment by bin456789** [comment]
> 我不使用ci参数，装出来也是cloud内核

这是故意的优化

> 请问一下加不加这个参数具体的区别是什么？VPS应该加还是不加？

https://github.com/bin456789/reinstall/issues/147#issuecomment-2320663078

https://wiki.debian.org/Cloud/SystemsComparison

官方文档也写得很模糊，详细的得看源码

https://salsa.debian.org/cloud-team/debian-cloud-images/-/tree/master/config_space/bookworm

> 还有能不能出一个加swap的教程/安装参数？

我觉得没必要

**Comment by bin456789** [comment]
> 所以到底该不该用ci参数呢？

随便，我建议不用

**Comment by GiT0WOalVjZ6ZhToNFeqLpdYByfodiQ4nksWmTL** [comment]
Debian的官方文档，写很相当脏，江湖上debian“大便”的称号，实在名不虚传。相比下，红帽的官方文梢，清析规范，而且有原生中文，十年安全更新。服务器没有特殊需求，完全可以用红帽系（rhel/centos/rocky/alma/oracle...）。

我们都非常感谢煎饼王的这个脚本！

**Comment by bin456789** [comment]
> 大佬赶快把swap功能加上吧，等着用你的脚本那

chatgpt帮到你

**Comment by bin456789** [comment]
> > > 大佬赶快把swap功能加上吧，等着用你的脚本那
> > 
> > 
> > chatgpt帮到你
> 
> 大佬球球了，加一个参数吧，照顾一下我们小白吧哭哭 https://github.com/leitbogioro/Tools/blob/master/README.md?plain=1#L196

https://kejilion.sh/

**Comment by joyoner** [comment]
> 有这种需求可以用云镜像安装 bash reinstall.sh debian --ci

使用了--ci 参数，网卡还是 enp6s18

**Comment by bin456789** [comment]
> > 有这种需求可以用云镜像安装 bash reinstall.sh debian --ci
> 
> 使用了--ci 参数，网卡还是 enp6s18

之前是 eth0 是因为 cloud-init 改的 eth0，镜像默认不是 eth0
现在新系统改成不用 cloud-init 了，所以变成了 enp6s18 这种形式

**Comment by joyoner** [comment]
> > > 有这种需求可以用云镜像安装 bash reinstall.sh debian --ci
> > 
> > 
> > 使用了--ci 参数，网卡还是 enp6s18
> 
> 之前是 eth0 是因为 cloud-init 改的 eth0，镜像默认不是 eth0 现在新系统改成不用 cloud-init 了，所以变成了 enp6s18 这种形式

现在如果仍需要eth0，有什么曲线的方案吗？

**Comment by bin456789** [comment]
> > > > 有这种需求可以用云镜像安装 bash reinstall.sh debian --ci
> > > 
> > > 
> > > 使用了--ci 参数，网卡还是 enp6s18
> > 
> > 
> > 之前是 eth0 是因为 cloud-init 改的 eth0，镜像默认不是 eth0 现在新系统改成不用 cloud-init 了，所以变成了 enp6s18 这种形式
> 
> 现在如果仍需要eth0，有什么曲线的方案吗？

安装后修改，具体问 deepseek
