### ISSUE TITLE
支持物理机重装吗

### ISSUE THREAD

**Issue by chenxudong2020** [bin456789/reinstall#209]

**Comment by bin456789** [comment]
理论上支持
实际上没测试过

**Comment by chenxudong2020** [comment]
我试试

**Comment by chenxudong2020** [comment]
debain重装失败了。。。。centos倒是成功了![IMG_20241130_184041.jpg](https://github.com/user-attachments/assets/e7c1e2b8-7920-4542-8ebf-b4cb566996f0)

**Comment by chenxudong2020** [comment]
![IMG_20241130_190452.jpg](https://github.com/user-attachments/assets/95ed5c32-58b7-4457-8000-83802377f6b7)

debain一直重装失败。。。无论哪个系统过来 貌似不存在firmware.cpio.gz文件

**Comment by bin456789** [comment]
下载源出问题了
https://github.com/sjtug/mirror-requests/issues/386

我换个下载源

**Comment by chenxudong2020** [comment]
更新下脚本吧 我在重新拉取下 一般用的最多就debain centos ubuntu alpine第三方的像腾讯系统 欧拉 等系统怕有后门

**Comment by bin456789** [comment]
更新了

**Comment by chenxudong2020** [comment]
问题解决了但是 通过alpine重装 centos和debian的时候多次出现如下报错 但是重新再来几次又可以成功
![1732974141188](https://github.com/user-attachments/assets/a4c574aa-d544-4139-808e-d22daff3c0fd)

**Comment by bin456789** [comment]
本机的alpine软件源不稳定，跟脚本无关

**Comment by chenxudong2020** [comment]
我是用你的alpine装的 源用的是自带的 不太明白你说的 是网不稳定吗

**Comment by chenxudong2020** [comment]
我是用你的alpine装的 源用的是自带的 不太明白你说的 是网不稳定吗

**Comment by bin456789** [comment]
不知道，alpine有时是这样
运行 `apk add` 会自动修复

**Comment by bin456789** [comment]
经测试是脚本的问题，先已修复
