### ISSUE TITLE
安装alibaba cloud 3的失败

### ISSUE THREAD

**Issue by Wind188** [bin456789/reinstall#212]
bash reinstall.sh redhat 9 --img='https://alinux3.oss-cn-hangzhou.aliyuncs.com/aliyun_3_x64_20G_nocloud_alibase_20240819.qcow2'

腾讯云服务器，没有安装成功，不知道是不是我的找的镜像文件问题

**Comment by bin456789** [comment]
已修复

**Comment by Wind188** [comment]
![image](https://github.com/user-attachments/assets/05c7dd85-7084-43df-ac7e-564649edfaa5)
今天测试成功了，但是我在启动的时候，我在vnc里面看见了这个

![Uploading image.png…]()

**Comment by bin456789** [comment]
那个报错可以忽略，不会对安装过程有任何影响
