### ISSUE TITLE
Windows was corrupted after reboot

### ISSUE THREAD

**Issue by SashaGoncharov19** [bin456789/reinstall#217]
Original system: Ubuntu 24.04
System to be installed: Windows 11

So, after reboot hetzner intsance, windows turned on in recovery mode. I tried to check if disk exists with windows installation, but i got nothing.
![image](https://github.com/user-attachments/assets/0b356061-40f7-4f2f-9d55-bcd1ddaee843)

For now i don't know if is possible to recovery image. If i can attach any logs, please give me an instruction where i can found this log.

**Comment by bin456789** [comment]
Did this screen appear after you successfully installed Windows, or did it show up during the installation process?

**Comment by bin456789** [comment]
It seems that your hard drive driver is not available in the WinRE environment. If you want to save your data, you should go to the Hetzner panel, mount the Windows PE ISO, and recover your files.

**Comment by SashaGoncharov19** [comment]
Hetzner provides only virtio and windows server iso files. I cant directly upload iso files into my hetzner account. Is any other way?

**Comment by bin456789** [comment]
The simplest method is to unattach the current hard drive, or create a snapshot and attach it to another instance, but I'm not sure if Hetzner supports this.

The alternative method is to mount the virtio ISO and use the `drvload` command to install the drivers (viostor.inf and vioscsi.inf). After that, you should be able to see the hard drive files, locate the `winre.wim`, and use the `dism` command to install the same drivers into the `winre.wim`. After restarting Windows, the system repair will be triggered automatically. If the repair fails, you can also mount the Windows ISO, which contains repair functionality as well.

**Comment by SashaGoncharov19** [comment]
So much troubles with it. I tried but it don't give any result. Just keep in mind that this trouble exists. Thanks for responses)

**Comment by bin456789** [comment]
The system failure to start is unrelated to the script.

As for recovery mode lacking the disk driver.
I manually installed Windows in VMware (using the vmscsi disk driver).
After installation, recovery mode did not include the vmscsi driver.
In other words, Windows recovery mode does not include third-party disk drivers, which surprised me, as I always thought it did.

**Comment by SashaGoncharov19** [comment]
Mb we can include it somehow?
