### ISSUE TITLE
dd完 Arch Linux之后并且升级内核到最新版之后，yay -S 安装后Docker无法启动

### ISSUE THREAD

**Issue by MelissaCampos9962MelissaCampos** [bin456789/reinstall#22]
请问这是镜像的问题？ 还是  Arch的内核太高 导致和Docker不兼容导致的呢？

Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.

运行 journalctl -xeu docker.service 后 显示：

Oct 28 23:20:21 archlinux systemd[1]: Starting Docker Application Container Engine...
░░ Subject: A start job for unit docker.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit docker.service has begun execution.
░░ 
░░ The job identifier is 860.
Oct 28 23:20:21 archlinux dockerd[21462]: time="2023-10-28T23:20:21.145807838+08:00" level=info msg="Starting up"
Oct 28 23:20:21 archlinux dockerd[21462]: time="2023-10-28T23:20:21.147081452+08:00" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
Oct 28 23:20:21 archlinux dockerd[21462]: time="2023-10-28T23:20:21.166440224+08:00" level=error msg="failed to mount overlay: no such device" storage-driver=overlay2
Oct 28 23:20:21 archlinux dockerd[21462]: time="2023-10-28T23:20:21.166554628+08:00" level=error msg="exec: \"fuse-overlayfs\": executable file not found in $PATH" storage-driver=fuse-overlayfs
Oct 28 23:20:21 archlinux dockerd[21462]: time="2023-10-28T23:20:21.171716088+08:00" level=info msg="Loading containers: start."
Oct 28 23:20:21 archlinux dockerd[21462]: time="2023-10-28T23:20:21.174033845+08:00" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module bridge not found in directory /lib/modules/6.5.7-arch1-1\nmodprobe: WARNING: Module br_netfilter not found in directory /lib/modules/6.5.7-arch1-1\n, error: exit status 1"
Oct 28 23:20:21 archlinux dockerd[21462]: time="2023-10-28T23:20:21.181704857+08:00" level=info msg="unable to detect if iptables supports xlock: 'iptables --wait -L -n': `iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.`" error="exit status 3"
Oct 28 23:20:21 archlinux dockerd[21462]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.9 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Oct 28 23:20:21 archlinux dockerd[21462]: Perhaps iptables or your kernel needs to be upgraded.
Oct 28 23:20:21 archlinux dockerd[21462]:  (exit status 3)
Oct 28 23:20:21 archlinux systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit docker.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Oct 28 23:20:21 archlinux systemd[1]: docker.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit docker.service has entered the 'failed' state with result 'exit-code'.
Oct 28 23:20:21 archlinux systemd[1]: Failed to start Docker Application Container Engine.
░░ Subject: A start job for unit docker.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit docker.service has finished with a failure.
░░ 
░░ The job identifier is 860 and the job result is failed.
Oct 28 23:20:23 archlinux systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ Automatic restarting of the unit docker.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Oct 28 23:20:23 archlinux systemd[1]: Starting Docker Application Container Engine...
░░ Subject: A start job for unit docker.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit docker.service has begun execution.
░░ 
░░ The job identifier is 942.
Oct 28 23:20:23 archlinux dockerd[21538]: time="2023-10-28T23:20:23.369514331+08:00" level=info msg="Starting up"
Oct 28 23:20:23 archlinux dockerd[21538]: time="2023-10-28T23:20:23.370410251+08:00" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
Oct 28 23:20:23 archlinux dockerd[21538]: time="2023-10-28T23:20:23.385898462+08:00" level=error msg="failed to mount overlay: no such device" storage-driver=overlay2
Oct 28 23:20:23 archlinux dockerd[21538]: time="2023-10-28T23:20:23.386037485+08:00" level=error msg="exec: \"fuse-overlayfs\": executable file not found in $PATH" storage-driver=fuse-overlayfs
Oct 28 23:20:23 archlinux dockerd[21538]: time="2023-10-28T23:20:23.388153703+08:00" level=info msg="Loading containers: start."
Oct 28 23:20:23 archlinux dockerd[21538]: time="2023-10-28T23:20:23.390815915+08:00" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module bridge not found in directory /lib/modules/6.5.7-arch1-1\nmodprobe: WARNING: Module br_netfilter not found in directory /lib/modules/6.5.7-arch1-1\n, error: exit status 1"
Oct 28 23:20:23 archlinux dockerd[21538]: time="2023-10-28T23:20:23.396156518+08:00" level=info msg="unable to detect if iptables supports xlock: 'iptables --wait -L -n': `iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.`" error="exit status 3"
Oct 28 23:20:23 archlinux dockerd[21538]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.9 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Oct 28 23:20:23 archlinux dockerd[21538]: Perhaps iptables or your kernel needs to be upgraded.
Oct 28 23:20:23 archlinux dockerd[21538]:  (exit status 3)
Oct 28 23:20:23 archlinux systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit docker.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Oct 28 23:20:23 archlinux systemd[1]: docker.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit docker.service has entered the 'failed' state with result 'exit-code'.
Oct 28 23:20:23 archlinux systemd[1]: Failed to start Docker Application Container Engine.
░░ Subject: A start job for unit docker.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit docker.service has finished with a failure.
░░ 
░░ The job identifier is 942 and the job result is failed.
Oct 28 23:20:25 archlinux systemd[1]: docker.service: Scheduled restart job, restart counter is at 2.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ Automatic restarting of the unit docker.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Oct 28 23:20:25 archlinux systemd[1]: Starting Docker Application Container Engine...
░░ Subject: A start job for unit docker.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit docker.service has begun execution.
░░ 
░░ The job identifier is 1024.
Oct 28 23:20:25 archlinux dockerd[21616]: time="2023-10-28T23:20:25.618712550+08:00" level=info msg="Starting up"
Oct 28 23:20:25 archlinux dockerd[21616]: time="2023-10-28T23:20:25.619827327+08:00" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
Oct 28 23:20:25 archlinux dockerd[21616]: time="2023-10-28T23:20:25.638269912+08:00" level=error msg="failed to mount overlay: no such device" storage-driver=overlay2
Oct 28 23:20:25 archlinux dockerd[21616]: time="2023-10-28T23:20:25.638310637+08:00" level=error msg="exec: \"fuse-overlayfs\": executable file not found in $PATH" storage-driver=fuse-overlayfs
Oct 28 23:20:25 archlinux dockerd[21616]: time="2023-10-28T23:20:25.640448631+08:00" level=info msg="Loading containers: start."
Oct 28 23:20:25 archlinux dockerd[21616]: time="2023-10-28T23:20:25.643135194+08:00" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module bridge not found in directory /lib/modules/6.5.7-arch1-1\nmodprobe: WARNING: Module br_netfilter not found in directory /lib/modules/6.5.7-arch1-1\n, error: exit status 1"
Oct 28 23:20:25 archlinux dockerd[21616]: time="2023-10-28T23:20:25.648241610+08:00" level=info msg="unable to detect if iptables supports xlock: 'iptables --wait -L -n': `iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to be upgraded.`" error="exit status 3"
Oct 28 23:20:25 archlinux dockerd[21616]: time="2023-10-28T23:20:25.720481284+08:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Oct 28 23:20:25 archlinux dockerd[21616]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.9 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Oct 28 23:20:25 archlinux dockerd[21616]: Perhaps iptables or your kernel needs to be upgraded.
Oct 28 23:20:25 archlinux dockerd[21616]:  (exit status 3)
Oct 28 23:20:25 archlinux systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit docker.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Oct 28 23:20:25 archlinux systemd[1]: docker.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit docker.service has entered the 'failed' state with result 'exit-code'.
Oct 28 23:20:25 archlinux systemd[1]: Failed to start Docker Application Container Engine.
░░ Subject: A start job for unit docker.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit docker.service has finished with a failure.
░░ 
░░ The job identifier is 1024 and the job result is failed.
Oct 28 23:20:27 archlinux systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ Automatic restarting of the unit docker.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Oct 28 23:20:27 archlinux systemd[1]: docker.service: Start request repeated too quickly.
Oct 28 23:20:27 archlinux systemd[1]: docker.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit docker.service has entered the 'failed' state with result 'exit-code'.
Oct 28 23:20:27 archlinux systemd[1]: Failed to start Docker Application Container Engine.
░░ Subject: A start job for unit docker.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit docker.service has finished with a failure.
░░ 
░░ The job identifier is 1106 and the job result is failed.

**Comment by bin456789** [comment]
我帮你百度的结果是安装 iptables-nft
