### ISSUE TITLE
centos9重装centos10报错

### ISSUE THREAD

**Issue by xkatld** [bin456789/reinstall#222]
原来的系统：centos9
要安装的系统：centos10
遇到的问题：截图或者登录 SSH 获取日志 /reinstall.log
![image](https://github.com/user-attachments/assets/b8dc199a-8a83-4086-a347-a60948d14f56)

Original system:
System to be installed:
Issues encountered: Screenshot or log in via SSH to get the logs from /reinstall.log

**Comment by xkatld** [comment]
centos10对架构有要求？

**Comment by bin456789** [comment]
> centos10对架构有要求？

是

**Comment by bin456789** [comment]
现在脚本会提前判断 cpu 是否支持
