### ISSUE TITLE
dd出错 国内机器 非大厂

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bin456789/reinstall#24]
<img width="1194" alt="image" src="https://github.com/bin456789/reinstall/assets/147643826/992b07c0-aaa9-4402-9e71-620f20671e51">

**Comment by bin456789** [comment]
现在脚本的 debian 国内源已改成清华源
如果要改其他国内源，运行脚本后改 /boot/grub/custom.cfg

**Comment by MalikWilliams1greher** [comment]
谢谢 大佬牛逼
