### ISSUE TITLE
win10企业版22h2 dd alpine-3.18失败

### ISSUE THREAD

**Issue by Salomens** [bin456789/reinstall#25]
国内环境，尝试替换github代理以及cmd设置代理都无法成功，cmd管理员模式下运行`reinstall.bat alpine-3.18`重装脚本提示`/usr/bin/bash: 行 1: /cygdrive/creinstall.sh: No such file or directory`自行重启电脑还是会进入windows系统，脚本是最新脚本
文件日志
[setup.log](https://github.com/bin456789/reinstall/files/13238699/setup.log)
[setup.log.full.log](https://github.com/bin456789/reinstall/files/13238713/setup.log.full.log)

**Comment by bin456789** [comment]
现在应该正常了
