### ISSUE TITLE
readme 疑似笔误

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bin456789/reinstall#27]
https://github.com/bin456789/reinstall#windows-iso-%E5%AE%89%E8%A3%85

<img width="737" alt="image" src="https://github.com/bin456789/reinstall/assets/147643826/cb6bd831-41f4-4de0-8619-289265eb68ac">

这里下面 是否应该是 reinstall.bat

**Comment by bin456789** [comment]
没错的
上面是在 windows 下运行
下面是在 安装 windows iso（在linux下运行）

**Comment by MalikWilliams1greher** [comment]
> 没错的 上面是在 windows 下运行 下面是在 安装 windows iso（在linux下运行）

Windows 可以 dd 到 windows吗

**Comment by bin456789** [comment]
可以，首页有写

**Comment by MalikWilliams1greher** [comment]
> 可以，首页有写

那你这个README.md可能真的写错了 我截图的部分是下面的部分，不是上面的 你一共写了两个一模一样的命令

**Comment by bin456789** [comment]
前面是简单示范
后面那个是详细解释

不过现在已经合并了
