### ISSUE TITLE
dd到 windows10 报错

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bin456789/reinstall#28]
我先从Windows dd到 alpine正常

在从alpine dd到 win10 iso 报错如下

<img width="1250" alt="image" src="https://github.com/bin456789/reinstall/assets/147643826/65e59509-342d-4a95-8991-6307740f3013">

怕你看不清，最高清就是这样了，手机屏幕小 ，因为是手机屏蔽，我ocr了，不一定准确 

Dounload Results:

gid lstatlavg speed Ipath-URI

======+====+===========+==

5009e1lOk 197KiB/sl//osrdr ivers/ Jin.iso

Status Legend:

COK〕 :dounload completed

mount: Pos/dr iversruirtio: WARNING: source ur ite-protected, nounted read-only.

Ok:47 MiB in 117 packages

https://ghps.cc/https://raw.githubusercontent.com/bin456789/rei 11/mainrwindows.xml 11/04 13:57:43 [NOTICE1 Doun load ing 1 item (s)

[#7c4205 6.7KiB/OB CN:1 DL :18K iB

11/04 13:57:44 [NOTICEJ Dounload complete://tmp/futounattend.xml

Dounload Results:

gid lstatlavg speed Ipath/URI

三=三三三三+=二==+===========+=======

7c42a5lOk 6.6kiB/sl//tmp/futounattend.xml

Status Legend:

(ok):dounload completed.

ERROR: "2" is not a ualid image in/os/installer/sources/boot.wim"1

Please specify a 1-based inage index Or

conta ined in the WIM archive, run

image name . To list the images

wininfo/os/installer/sources/boot.uim

ERROR: Exiting uith error code 18:

Tr ied to select an

Line 1811 return 10

image that does not exist in the WIM

u immountru Sboot_win 2 /win/

Welcone to Alpine Linux 3.18

Kerne1 6.1.55-0-uirt on an x86_64 (/deu/ttu1)

**Comment by bin456789** [comment]
要用官方的镜像

**Comment by MalikWilliams1greher** [comment]
> 要用官方的镜像

谢谢大佬 换到官方版后可以了，请问后期计划支持精简版系统Windows系统嘛 😂 官方版太占内存了

**Comment by bin456789** [comment]
不打算支持
