### ISSUE TITLE
移动云windows dd centos报错

### ISSUE THREAD

**Issue by haohaihaohaiyo** [bin456789/reinstall#30]
![D5889604EC0FA25943741CF44CE9ADAE](https://github.com/bin456789/reinstall/assets/53995488/21ee7dbe-97cd-41ff-84a2-cd685ecfbd96)
换ubuntu和debian都这样

**Comment by bin456789** [comment]
不加任何参数安装debian 看下是什么报错

**Comment by haohaihaohaiyo** [comment]
![Uploading 1.jpg…]()

**Comment by haohaihaohaiyo** [comment]
用的reinstall.bat debian

**Comment by haohaihaohaiyo** [comment]
![Uploading 1.jpg…]()
卡住了

**Comment by haohaihaohaiyo** [comment]
![1](https://github.com/bin456789/reinstall/assets/53995488/155894aa-23c2-41a6-9231-6c15b827ec62)

**Comment by bin456789** [comment]
试下 reinstall.bat debian
然后打开 c:\grub.cfg，删除 console=ttyS0
再重启

**Comment by haohaihaohaiyo** [comment]
连着 console=ttyS0后面的逗号删除后能进入
![3](https://github.com/bin456789/reinstall/assets/53995488/2c2d0b98-1216-48d9-9b5a-1512ee8f581c)

**Comment by bin456789** [comment]
目测 dhcp 获取了ip，但网络不通
印象中按 crtl+a 3 可以运行命令
运行 ip addr 看下有没有 ip
有 ip 的话就不关我事了

**Comment by haohaihaohaiyo** [comment]
![4](https://github.com/bin456789/reinstall/assets/53995488/603d1e2b-ce2f-4853-abc5-5304ac0d90d8)
显示这样的

**Comment by bin456789** [comment]
回到windows下，看下网卡是不是设置了静态ip
再试下设置成自动获取ip，看下能不能上网

**Comment by bin456789** [comment]
脚本已经更新
如果alpine下获取的ip和windows的不同
那么新脚本应该有用

**Comment by haohaihaohaiyo** [comment]
感谢，感谢。现在装上了

**Comment by Rainnnray** [comment]
刚用一台新机子测试装ubuntu，新脚本好像还是没正确获取ip，我看windows下是手动设置的ip

**Comment by bin456789** [comment]
> 刚用一台新机子测试装ubuntu，新脚本好像还是没正确获取ip，我看windows下是手动设置的ip 截图

添加 --ci

**Comment by Rainnnray** [comment]
> > 刚用一台新机子测试装ubuntu，新脚本好像还是没正确获取ip，我看windows下是手动设置的ip 截图
> 
> 添加 --ci

由于未获取到网络，现在还能在系统内重新dd嘛？

**Comment by bin456789** [comment]
> > > 刚用一台新机子测试装ubuntu，新脚本好像还是没正确获取ip，我看windows下是手动设置的ip 截图
> > 
> > 
> > 添加 --ci
> 
> 由于未获取到网络，现在还能在系统内重新dd嘛？

不知道你安装进行到哪个步骤
如果一进入ubuntu安装环境就报错，还没实际安装的话
可以重启 ，再grub菜单按e，删除 autoinstall cloud-config-url=xxx，然后手动安装

如果安装到一半报错
可以dd https://mirrors.nju.edu.cn/alpine/latest-stable/releases/x86_64/alpine-virt-3.18.4-x86_64.iso 到硬盘，重启安装alpine 再换ubuntu
