### ISSUE TITLE
移动云windows dd ubuntu报错

### ISSUE THREAD

**Issue by waveCodeSite** [bin456789/reinstall#31]
![image](https://github.com/bin456789/reinstall/assets/131228850/45438071-bc69-4ea7-ad1d-ea4c71c08701)

**Comment by bin456789** [comment]
输入tail那行命令才能看到是什么错误

**Comment by waveCodeSite** [comment]
![image](https://github.com/bin456789/reinstall/assets/131228850/6c7e8985-8be6-4d3c-b622-3d6ebffe1e33)

**Comment by waveCodeSite** [comment]
域名不通，在这个系统里面怎么重新运行dd啊？

**Comment by bin456789** [comment]
ash /tmp/trans.sh
但是不知道为什么 IP 识别成在国外

**Comment by waveCodeSite** [comment]
很迷
