### ISSUE TITLE
腾讯云轻量云上海 dd debian12 卡住半小时以上了

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bin456789/reinstall#32]
<img width="975" alt="image" src="https://github.com/bin456789/reinstall/assets/147643826/e5a90313-f708-4164-9982-3c6e0044a455">

**Comment by bin456789** [comment]
https://github.com/bin456789/reinstall/issues/19#issuecomment-1778504017

**Comment by waveCodeSite** [comment]
为啥不直接在腾讯的控制台重装尼？

**Comment by MalikWilliams1greher** [comment]
> 为啥不直接在腾讯的控制台重装尼？

你猜我为什么要dd呢
