### ISSUE TITLE
大佬 为什么Ubuntu 22.04 中/etc/apt/sources.list里面写的源 和 实际用的源不一致？怎么做到的？

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bin456789/reinstall#33]
刚装好的纯净系统。

/etc/apt/sources.list里面是cn.archive.ubuntu.com/ubuntu 但是

更新的时候走的清华源 

怎么设置的😂

<img width="1114" alt="image" src="https://github.com/bin456789/reinstall/assets/147643826/0dd77c4b-1c7a-4e39-a21c-45f4bf7ea111">

**Comment by bin456789** [comment]
https://www.v2ex.com/t/982665
