### ISSUE TITLE
Azure是不是没法用这个将server 2016降回2012

### ISSUE THREAD

**Issue by findyy99** [bin456789/reinstall#35]
安装grub到EFI的时候报错
`Error: Line 913 return 1
    id=$(bcdedit /copy '{bootmgr}' /d "$(get_entry_name)" | grep -o '{.*}')`
<img width="577" alt="image" src="https://github.com/bin456789/reinstall/assets/26852735/5d1048a1-4779-4408-84e5-afcf226080cc">

**Comment by bin456789** [comment]
单独运行 bcdedit /copy '{bootmgr}' /d 123 看下是什么错误

如果跟安全启动有关，那就关闭安全启动
