### ISSUE TITLE
移动云电脑 DD系统报错

### ISSUE THREAD

**Issue by coldnight9** [bin456789/reinstall#36]
![QQ截图20231113102726](https://github.com/bin456789/reinstall/assets/80202197/bc6fcb44-7db6-4fd9-87ed-52df4681bc82)
![QQ截图20231113102758](https://github.com/bin456789/reinstall/assets/80202197/3f1152a2-32d3-4285-a604-f2ecb81a5351)
大佬看看因为什么报错
reinstall.bat alpine-3.18
reinstall.bat debian-11
reinstall.bat debian 都报错

**Comment by coldnight9** [comment]
![QQ截图20231113102758](https://github.com/bin456789/reinstall/assets/80202197/4f2f5d67-eb30-4830-8d67-8cec2ba24a89)
最开始的报错是这个

**Comment by bin456789** [comment]
将 reinstall.sh 76行 $_is_in_china 改为 true 再运行

**Comment by coldnight9** [comment]
> 将 reinstall.sh 76行 $_is_in_china 改为 true 再运行
谢谢大佬，目前好像正常运行了！
