### ISSUE TITLE
dd后ipv6网卡会掉

### ISSUE THREAD

**Issue by tanglu1323123** [bin456789/reinstall#4]
我看萌咖大佬的脚本也是dd后ipv6网卡会消失

请问有办法解决吗？

**Comment by leitbogioro** [comment]
Debian/Kali 系 IPv6 部分需要在安装系统后手工配置，否则重装后会掉 IPv6，你需要安装哪个系统？机器如果原来 IPv4 和 IPv6 都有，我的脚本重装后 IPv6 部分都能自动配好，有问题去我项目里提 issues:
https://github.com/leitbogioro/Tools
中文文档：
https://www.nodeseek.com/post-9383-1

**Comment by tangluya** [comment]
使用 -img=
ipv6网卡还是无法添加吗？

不过可以添加v4已经够用了
