### ISSUE TITLE
移动云无法下载，北京移动，老是报错12002

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bin456789/reinstall#40]
<img width="938" alt="image" src="https://github.com/bin456789/reinstall/assets/147643826/312fb8e3-6fb9-42a0-94f2-0df9b3db0db6">

**Comment by MalikWilliams1greher** [comment]
然后我通过手动下载reinstall.bat到移动云主机 然后用dd命令的时候 也是经常提示这个 ，最后基础的组件没下载下来，导致无法进入dd流程

是移动网络的问题吗

**Comment by MalikWilliams1greher** [comment]
挂代理 走国外源下载 最后卡在这里了

<img width="518" alt="image" src="https://github.com/bin456789/reinstall/assets/147643826/639b39a8-47cb-4245-ac22-17823a27f914">

**Comment by devhaozi** [comment]
![图片](https://github.com/bin456789/reinstall/assets/115467771/03b1e65a-5b65-40a0-b7cc-7072a09a7808)

脚本内置的 GitHub 代理 ghps.cc 受限制了，替换成 mirror.ghproxy.com 即可正常使用。

**Comment by MalikWilliams1greher** [comment]
> ![图片](https://private-user-images.githubusercontent.com/115467771/285588308-03b1e65a-5b65-40a0-b7cc-7072a09a7808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MTIzODUsIm5iZiI6MTcwMDkxMjA4NSwicGF0aCI6Ii8xMTU0Njc3NzEvMjg1NTg4MzA4LTAzYjFlNjVhLTViNjUtNDBhMC1iN2NjLTcwNzJhMDlhNzgwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxMTM0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODYzMWU4MTNhMDc3NjFjNTlkZTk0OWY0ODUzYzU3Zjc3MzEyOWIxNDYzNTlmZDc0YjAxMTY3Njg2ZjUyNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2gzOBjzwSLaAPRmMFtRDkf4fBFz8_L92IJzd9HofzjQ)
> 
> 脚本内置的 GitHub 代理 `ghps.cc` 受限制了，替换成 `mirror.ghproxy.com` 即可正常使用。

谢谢大佬 我今天整了一天了 是要编辑脚本内容把所有的ghps.cc都换掉是吧

**Comment by devhaozi** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/115467771/285588308-03b1e65a-5b65-40a0-b7cc-7072a09a7808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MTIzODUsIm5iZiI6MTcwMDkxMjA4NSwicGF0aCI6Ii8xMTU0Njc3NzEvMjg1NTg4MzA4LTAzYjFlNjVhLTViNjUtNDBhMC1iN2NjLTcwNzJhMDlhNzgwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxMTM0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODYzMWU4MTNhMDc3NjFjNTlkZTk0OWY0ODUzYzU3Zjc3MzEyOWIxNDYzNTlmZDc0YjAxMTY3Njg2ZjUyNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2gzOBjzwSLaAPRmMFtRDkf4fBFz8_L92IJzd9HofzjQ)
> > 脚本内置的 GitHub 代理 `ghps.cc` 受限制了，替换成 `mirror.ghproxy.com` 即可正常使用。
> 
> 谢谢大佬 我今天整了一天了 是要编辑脚本内容把所有的ghps.cc都换掉是吧

只有一处

**Comment by MalikWilliams1greher** [comment]
> > > ![图片](https://private-user-images.githubusercontent.com/115467771/285588308-03b1e65a-5b65-40a0-b7cc-7072a09a7808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MTIzODUsIm5iZiI6MTcwMDkxMjA4NSwicGF0aCI6Ii8xMTU0Njc3NzEvMjg1NTg4MzA4LTAzYjFlNjVhLTViNjUtNDBhMC1iN2NjLTcwNzJhMDlhNzgwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxMTM0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODYzMWU4MTNhMDc3NjFjNTlkZTk0OWY0ODUzYzU3Zjc3MzEyOWIxNDYzNTlmZDc0YjAxMTY3Njg2ZjUyNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2gzOBjzwSLaAPRmMFtRDkf4fBFz8_L92IJzd9HofzjQ)
> > > 脚本内置的 GitHub 代理 `ghps.cc` 受限制了，替换成 `mirror.ghproxy.com` 即可正常使用。
> > 
> > 
> > 谢谢大佬 我今天整了一天了 是要编辑脚本内容把所有的ghps.cc都换掉是吧
> 
> 只有一处

感谢大佬 已经进入dd流程了 如果想自己搭建一个代理站 自己用 怎么搭建 就是类似ghps.cc和mirror.ghproxy.com这种的

**Comment by devhaozi** [comment]
> > > > ![图片](https://private-user-images.githubusercontent.com/115467771/285588308-03b1e65a-5b65-40a0-b7cc-7072a09a7808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MTIzODUsIm5iZiI6MTcwMDkxMjA4NSwicGF0aCI6Ii8xMTU0Njc3NzEvMjg1NTg4MzA4LTAzYjFlNjVhLTViNjUtNDBhMC1iN2NjLTcwNzJhMDlhNzgwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxMTM0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODYzMWU4MTNhMDc3NjFjNTlkZTk0OWY0ODUzYzU3Zjc3MzEyOWIxNDYzNTlmZDc0YjAxMTY3Njg2ZjUyNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2gzOBjzwSLaAPRmMFtRDkf4fBFz8_L92IJzd9HofzjQ)
> > > > 脚本内置的 GitHub 代理 `ghps.cc` 受限制了，替换成 `mirror.ghproxy.com` 即可正常使用。
> > > 
> > > 
> > > 谢谢大佬 我今天整了一天了 是要编辑脚本内容把所有的ghps.cc都换掉是吧
> > 
> > 
> > 只有一处
> 
> 感谢大佬 已经进入dd流程了 如果想自己搭建一个代理站 自己用 怎么搭建 就是类似ghps.cc和mirror.ghproxy.com这种的

去 mirror.ghproxy.com 上面有开源地址

**Comment by devhaozi** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/115467771/285588308-03b1e65a-5b65-40a0-b7cc-7072a09a7808.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNTU1ODUsIm5iZiI6MTcwMTA1NTI4NSwicGF0aCI6Ii8xMTU0Njc3NzEvMjg1NTg4MzA4LTAzYjFlNjVhLTViNjUtNDBhMC1iN2NjLTcwNzJhMDlhNzgwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QwMzIxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOWQ1M2E5YmRiZTJmZjljOWI1YmM0ZWZlYWQwNmQ3YjE2ODllYjdjZTZmMDEwODc2YWY2ODkxZjI3NDZkYTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7EVz-ElO-ldigx2LWk_uEi3Kp9wu2Ag2sn1avkcjrNg)
> > 脚本内置的 GitHub 代理 `ghps.cc` 受限制了，替换成 `mirror.ghproxy.com` 即可正常使用。
> 
> 替换完还是提示错误 ![QQ截图20231127112303](https://private-user-images.githubusercontent.com/85274173/285713399-1b977973-0078-48e7-8283-fc5e39cad17c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNTU3NjcsIm5iZiI6MTcwMTA1NTQ2NywicGF0aCI6Ii84NTI3NDE3My8yODU3MTMzOTktMWI5Nzc5NzMtMDA3OC00OGU3LTgyODMtZmM1ZTM5Y2FkMTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAzMjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjVjZDk4MTIwNGM3NjRiNzkyMWQ2OGU4MDVjN2UwMjRmZTllZWE2ZGQ3M2MzMDc2NTgzOWIzZTZkMWE1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6kHfMRP4iRCmndMOK2oPTp4h7JY4PuciMPR1jIDgvto)

替换错了？或者服务器连不上替换的节点。
