### ISSUE TITLE
错误提示Error: Line 65 return 22     command curl --insecure --connect-timeout 5 --retry 2 --retry-delay 1 -f "$@"

### ISSUE THREAD

**Issue by tingyuloulala** [bin456789/reinstall#41]
windows下安装alpine时提示如下，已经替换ghps.cc，并且好几个系统都有类似提示
***** INSTALL GRUB FOR BIOS *****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0    854      0 --:--:-- --:--:-- --:--:--   862
100 1539k  100 1539k    0     0  2342k      0 --:--:-- --:--:-- --:--:-- 3932k
                        {1c41f649-1637-52f1-aea8-f96bfebeecc8}
bootsequence            {1c41f649-1637-52f1-aea8-f96bfebeecc8}
identifier              {1c41f649-1637-52f1-aea8-f96bfebeecc8}
The operation completed successfully.
The entry {1c41f649-1637-52f1-aea8-f96bfebeecc8} was successfully created.
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
The operation completed successfully.
***** DOWNLOAD VMLNUZ AND INITRD *****
http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.18/releases/x86_64/netboot/vmlinuz-virt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8932k  100 8932k    0     0  15.1M      0 --:--:-- --:--:-- --:--:-- 15.1M
http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.18/releases/x86_64/netboot/initramfs-virt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7056k  100 7056k    0     0  15.6M      0 --:--:-- --:--:-- --:--:-- 15.6M
***** MOD ALPINE INITRD *****
39882 块
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    14    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 403
Error: Line 65 return 22
    command curl --insecure --connect-timeout 5 --retry 2 --retry-delay 1 -f "$@"

**Comment by bin456789** [comment]
重新下载脚本运行，看下是哪个链接报错

**Comment by tingyuloulala** [comment]
> 重新下载脚本运行，看下是哪个链接报错

用新更新的脚本没问题了，非常感谢！
