### ISSUE TITLE
有没有人使用脚本安装debian12后，/etc/network/interfaces里有个yhsrv.com？

### ISSUE THREAD

**Issue by la0wei** [bin456789/reinstall#42]
vps服务商racknerd，以前是dhcp获取地址，现在估计改成模板内置脚本获取ip了，dd时需要手动配置ip

安装完因为有事就放在一边，只设置了10位密码，密码有小写字母，符号，数字。自己也从未用过该密码

第二天因为下载github脚本时解析出的地址是ipv6，我就想进/etc/network/interfaces手动配置ip，发现最后一行多了个 domainname yhsrv.com

用last也没看出什么异常登录，毕竟新装系统，就没几次登录。

interfaces文件与/etc/network/内有几个文件修改时间是一致的，但是时区的关系，不记得是否安装时间

安全起见就重新安装回vps自带模板系统。

**Comment by bin456789** [comment]
我查到 yhsrv 跟racknerd 有某种联系
可能是上游跟下游的关系
https://myip.ms/view/blacklist/1806619193/107.174.210.57

这个 yhsrv.com 应该是 dhcp 获取的某种信息

**Comment by bin456789** [comment]
测试了一下
debian 安装时会获取 RDNS 信息，并写到以下文件中，静态IP的机器也如此

/etc/resolv.conf
search 11.22.33.44.xxx.com

/etc/network/interfaces
dns-search 11.22.33.44.xxx.com

如果你的服务商/上游将你机器的 RDNS设置成 host-11-22-33-44-by.yhsrv.com
那么上面的文件就会有yhsrv.com的字样
