### ISSUE TITLE
azure现在无法dd了

### ISSUE THREAD

**Issue by mucstudio** [bin456789/reinstall#43]
windows 2016
之前可以，现在换了好几台电脑都是同样的问题出现。

***** INSTALL GRUB FOR EFI *****
Error: Line 927 return 1
    id=$(bcdedit /copy '{bootmgr}' /d "$(get_entry_name)" | grep -o '{.*}')

**Comment by mucstudio** [comment]
C:\Windows\system32>bcdedit /copy '{bootmgr}' /d 123
The specified entry identifier is not valid.
The parameter is incorrect.

**Comment by bin456789** [comment]
> C:\Windows\system32>bcdedit /copy '{bootmgr}' /d 123 The specified entry identifier is not valid. The parameter is incorrect.

在powershell里运行 bcdedit /copy '{bootmgr}' /d 123 看看
