### ISSUE TITLE
求新增dd到macOS

### ISSUE THREAD

**Issue by MalikWilliams1greher** [bin456789/reinstall#44]
想玩黑苹果服务器 😄

**Comment by bin456789** [comment]
太高端，搞不了

**Comment by Oio0** [comment]
NB

**Comment by m4d3bug** [comment]
现在ai那么强了，有机会搞这个吗？ docker版都有了 https://github.com/sickcodes/docker-osx

**Comment by yanglin2025** [comment]
好幸运你们，https://inst.sh 刚刚宣布支持osx， 不过好像你们需要独立研究高级部分

https://lowendtalk.com/discussion/220517/inst-sh-how-to-reinstall-linux-into-hackintosh-using-instpanel-with-dmg-support-reverse-works-too
