### ISSUE TITLE
dd一个新系统fydeos失败

### ISSUE THREAD

**Issue by haohaihaohaiyo** [bin456789/reinstall#47]
求大佬帮帮忙，想dd一个即是linux，又能使用安卓的，找了一个国产的，基于chromeos的。
使用的这个镜像https://fydeos.com/download/pc/apu。
命令用的
reinstall.bat dd --img=https://download.fydeos.io/FydeOS_for_PC_apu_v17.1-com-stable.img.xz

然后结果是卡booting the kernel.
![Screenshot_2023-12-05-07-55-24-62_d8015f693ef98e8df99715a8c6ac60cd](https://github.com/bin456789/reinstall/assets/53995488/73f32203-94fd-4c81-acbf-09d09fba28f7)

**Comment by bin456789** [comment]
太高端，搞不了
