### ISSUE TITLE
command curl --insecure --connect-timeout 5 --retry 2 --retry-delay 1

### ISSUE THREAD

**Issue by leanovv** [bin456789/reinstall#48]
***** MOD ALPINE INITRD *****
46090 块
https://ghps.cc/https://raw.githubusercontent.com/bin456789/reinstall/main/trans.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    16    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 429
Warning: Problem : HTTP error. Will retry in 1 seconds. 2 retries left.
  0    16    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 429
Warning: Problem : HTTP error. Will retry in 1 seconds. 1 retries left.
  0    16    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 429
Error: Line 67 return 22
    command curl --insecure --connect-timeout 5 --retry 2 --retry-delay 1 -f "$@"

更新到新的脚本还是提示这个错误。

**Comment by bin456789** [comment]
现在应该可以了
