### ISSUE TITLE
ubuntu DD win 用 ISO镜像遇到问题

### ISSUE THREAD

**Issue by hiseller** [bin456789/reinstall#49]
用的是ISO镜像，换了几个不同的镜像 都卡在最后一步。
![Snipaste_2023-12-20_23-10-29](https://github.com/bin456789/reinstall/assets/62457398/148c9fbd-8f25-4af6-90ab-4f8c6bdd5c78)

**Comment by bin456789** [comment]
说下你的 --iso和 --image-name 参数
目测 -image-name 不正确

**Comment by hiseller** [comment]
---------------------------------------------------------------------------------   
curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh
bash reinstall.sh windows \
     --iso='https://archive.org/download/en-us_windows_server_2019_x64_dvd_f9475476/en-us_windows_server_2019_x64_dvd_f9475476.iso' \
     --image-name='Windows Server 2019 Standard'
---------------------------------------------------------------------------------
curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh
bash reinstall.sh windows \
     --iso='https://archive.org/download/en-us_windows_server_2022_updated_nov_2022_x64_dvd_8d436d40/en-us_windows_server_2022_updated_nov_2022_x64_dvd_8d436d40.iso' \
     --image-name='Windows Server 2022 Standard'
--------------------------------------------------------------------------------- 
---------------------------------------------------------------------------------
curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh
bash reinstall.sh windows \
     --iso='https://archive.org/download/m-10-p-22-h-2-e_202304/M10P22H2E.iso' \
     --image-name='Windows 10 Pro'
--------------------------------------------------------------------------------- 
---------------------------------------------------------------------------------
curl -O https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh
bash reinstall.sh windows \
     --iso='https://archive.org/download/windows-10-lite-edition-19h2-x64/Windows%2010%20Lite%20Edition%2019H2%20x64.iso' \
     --image-name='Windows 10 Pro'
--------------------------------------------------------------------------------- 
以上ISO都试过，都是在最后一步

**Comment by bin456789** [comment]
前两个正确的名称应是
Windows Server 2019 ServerStandard
Windows Server 2022 ServerStandard

后两个不是官方镜像，不支持

**Comment by hiseller** [comment]
谢谢大佬，已解决
