### ISSUE TITLE
Ubuntu重装到Windows, 现在是在alpine, 该怎么进一步操作?

### ISSUE THREAD

**Issue by nonlog** [bin456789/reinstall#5]
我使用了
```
bash reinstall.sh windows \
    --iso=https://archive.org/download/tiny-10-NTDEV/tiny10%2023h1%20x64.iso \
    --image-name='Windows 10 Enterprise LTSC 2021'
reboot
``` 
现在重启是alpine, 请问下一步怎么做?

**Comment by bin456789** [comment]
image-name不对？可以用dism++打开iso看下image-name

**Comment by bin456789** [comment]
怕机器失联的话，可以现在安装alpine防止失联
umount -R /os /iso /wim
setup-alpine

**Comment by bin456789** [comment]
dism++
文件，打开映象文件
![微信图片_20230705184358](https://github.com/bin456789/reinstall/assets/7548515/b1bc6419-4beb-46da-b99c-a332cba92042)

**Comment by bin456789** [comment]
那就不清楚了，你可以试下原版有没有问题

**Comment by bin456789** [comment]
这个镜像是esd格式的，不是官方常用的wim格式
目前脚本不支持，所以出错

**Comment by KyonCN** [comment]
> 已经失联了😭 运行了setup-alpine到输密码那里连着敲回车, 断开就连不上了

ubuntu装Ubuntu 重启后变alpine 在同样位置失联了

**Comment by bin456789** [comment]
> 

装ubuntu，中间会重启到alpine，然后会再重启安装ubuntu
除非在vnc中看到出错，或者在alpine里输入`tail -f /reinstall.log` 看到出错，否则不要在alpine里乱来

**Comment by bin456789** [comment]
> > 已经失联了😭 运行了setup-alpine到输密码那里连着敲回车, 断开就连不上了
> 
> ubuntu装Ubuntu 重启后变alpine 在同样位置失联了

装ubuntu，中间会重启到alpine，然后会再重启安装ubuntu
除非在vnc/web看到出错，或者在alpine里输入tail -f /reinstall.log 看到出错，否则不要在alpine里乱来

**Comment by KyonCN** [comment]
> > > 已经失联了😭 运行了setup-alpine到输密码那里连着敲回车, 断开就连不上了
> > 
> > 
> > ubuntu装Ubuntu 重启后变alpine 在同样位置失联了
> 
> 装ubuntu，中间会重启到alpine，然后会再重启安装ubuntu 除非在vnc/web看到出错，或者在alpine里输入tail -f /reinstall.log 看到出错，否则不要在alpine里乱来

明白了，谢谢大佬

**Comment by bin456789** [comment]
@happy201807 
下载一份 trans.sh，将
xda=$(ls /dev/ | grep -Ex 'sda|hda|xda|vda|xvda|nvme0n1') 改成
xda=vda
运行 trans.sh

**Comment by bin456789** [comment]
@happy201807 
脚本昨天更新，修复了这种情况
按正常步骤安装，不用修改

**Comment by bin456789** [comment]
@happy201807 
日志太短，运行这个看看 tail -50 /reinstall.log

**Comment by bin456789** [comment]
@happy201807 
emmm，还是不够长
索性输入 `cat /reinstall.html` 吧

**Comment by bin456789** [comment]
@happy201807 
已修复，现在应该没问题了

**Comment by bin456789** [comment]
@happy201807 
是之前那台双硬盘机？
那大概是 sda 被 windows 识别为第一个硬盘，所以安装失败
linux 下运行 lspci -nn  我看下有没有办法处理

**Comment by bin456789** [comment]
@happy201807 
试下用这个，参数不变
不行也没办法了
curl -O https://raw.githubusercontent.com/bin456789/reinstall/multidisk-win/reinstall.sh
