### ISSUE TITLE
移动云电脑  政企版  安装之后123@@@提示密码不正确

### ISSUE THREAD

**Issue by stefma2** [bin456789/reinstall#50]
certutil -urlcache -f -split https://ghps.cc/https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.bat

./reinstall.bat windows --iso='https://drive.massgrave.dev/zh-cn_windows_11_business_editions_version_23h2_x64_dvd_2a79e0f1.iso' --image-name='Windows 11 Pro'

安装好win11 123@@@登录提示密码不正确

**Comment by bin456789** [comment]
这个密码肯定是对的
测试时试了无数遍了

**Comment by bin456789** [comment]
而且脚本也只有这个密码

这个 issue 就先关闭了
