### ISSUE TITLE
win11执行脚本存在无法执行exe

### ISSUE THREAD

**Issue by zhaoboy9692** [bin456789/reinstall#51]
win11执行脚本存在无法访问tmp路径
大致排查是因为 call:download 下载文件出错，下载的文件不存在，作者是否考虑使用 curl -o？
改成curl http://www.cloudflare.com/cdn-cgi/trace -o %tmp%\geoip 这样的格式？

**Comment by bin456789** [comment]
> win11执行脚本存在无法访问tmp路径 大致排查是因为 call:download 下载文件出错，下载的文件不存在

关掉杀毒软件即可

> 是否考虑使用 curl -o

win10之前没有 curl
部分dd的系统也精简了powershell
唯有用 certutil，缺点就是会被杀毒软件阻止

**Comment by zhaoboy9692** [comment]
> > win11执行脚本存在无法访问tmp路径 大致排查是因为 call:download 下载文件出错，下载的文件不存在
> 
> 关掉杀毒软件即可
> 
> > 是否考虑使用 curl -o
> 
> win10之前没有 curl 部分dd的系统也精简了powershell 唯有用 certutil，缺点就是会被杀毒软件阻止

thanks
