### ISSUE TITLE
移动云电脑 政企版 DD报错

### ISSUE THREAD

**Issue by coldnight9** [bin456789/reinstall#52]
mv: 无法将'/reinstall-initrd' 移动至'/cygdrive/C/reinstall-initrd': Device or resource busy
Error: Line 1542 return 1
        is_have_initrd && mv /reinstall-initrd /cygdrive/$c/

![90a31b3adad4c5b9addb5ce71d562da2](https://github.com/bin456789/reinstall/assets/80202197/58866cca-82d8-437a-9d10-ffafb5a3ab05)

**Comment by coldnight9** [comment]
请问这是什么问题导致的。

**Comment by coldnight9** [comment]
> 执行命令 reinstall.bat alpine-3.18 
mv: 无法将'/reinstall-initrd' 移动至'/cygdrive/C/reinstall-initrd': Device or resource busy Error: Line 1542 return 1 is_have_initrd && mv /reinstall-initrd /cygdrive/$c/
> 
> ![90a31b3adad4c5b9addb5ce71d562da2](https://private-user-images.githubusercontent.com/80202197/298403142-58866cca-82d8-437a-9d10-ffafb5a3ab05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NjE3MzMsIm5iZiI6MTcwNTg2MTQzMywicGF0aCI6Ii84MDIwMjE5Ny8yOTg0MDMxNDItNTg4NjZjY2EtODJkOC00MzdhLTlkMTAtZmZhZmI1YTNhYjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE4MjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNTRkNDZiZWJlNTVkYTQyZWU4NjAzNWE2ZjdiMmJkMzA5NjBhYWMwMGZmZWU2YjQ0ODRlZWEzZWY0Mzc4MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FMRLkdtKpfp8SyKQAW-aGVeqnencOt6qqT__GbaxsUs)

**Comment by coldnight9** [comment]
执行命令 reinstall.bat alpine-3.18

**Comment by bin456789** [comment]
现在没用到这条命令，不会再有这个问题了
