### ISSUE TITLE
移动云电脑 安装完进入系统界面后无法继续，提示找不到驱动器

### ISSUE THREAD

**Issue by Curtaun** [bin456789/reinstall#55]
![Screenshot_2024-01-30-00-41-43-458_com cmss cloudcomputer](https://github.com/bin456789/reinstall/assets/30548071/e6d88a40-fbc2-4765-8040-6608f5e4aa2b)

**Comment by Curtaun** [comment]
用的移动云政企版  系统是后台重新安装过就进行dd的

**Comment by Curtaun** [comment]
又重装了一遍，这次没问题了，很奇怪

**Comment by bin456789** [comment]
第一次安装，应该是加载硬盘控制器驱动后的5秒内，cpu不足，没刷新出硬盘分区
脚本到时会改动下，适配这种情况

**Comment by bin456789** [comment]
已更新脚本，应该不会再出现这种情况了
