### ISSUE TITLE
Windows DD BUG

### ISSUE THREAD

**Issue by DDCHINA0** [bin456789/reinstall#59]
![](https://i.miji.bid/2024/02/05/25c0e4cd426e7365d16fece84830bf21.jpeg)

**Comment by DDCHINA0** [comment]
* failed because we are using /


* ERROR: mount-ro failed to start

**Comment by bin456789** [comment]
正常现象，不用管

**Comment by DDCHINA0** [comment]
进行到最后无法进入系统

**Comment by bin456789** [comment]
是什么画面？如果是1楼的图，试下强制重启

**Comment by DDCHINA0** [comment]
这个走完会正常重启到win，开机转圈之后会黑屏没有反应

**Comment by bin456789** [comment]
dd的话，这就不关脚本事了
或者你试下用脚本安装windows iso
