### ISSUE TITLE
为什么我在移动电脑从windows dd到ubuntu会自动安装成功,都正常,但是在台式机上从windows DD 到ubuntu 需要操作流程?

### ISSUE THREAD

**Issue by dev-kang** [bin456789/reinstall#60]
关键操作流程也不知道如何进行选择,导致现在失败,进入了initramfs模式,不知道如何进行下一步了. 只能再重新安装系统?

**Comment by bin456789** [comment]
不知道
如果是在alpine的initramfs下，重启就回到原系统
如果是在ubuntu的initramfs下，重启在grub下删除 autoinstall 应该能手动安装，注意不能改动分区

**Comment by dev-kang** [comment]
> 不知道 如果是在alpine的initramfs下，重启就回到原系统 如果是在ubuntu的initramfs下，重启在grub下删除 autoinstall 应该能手动安装，注意不能改动分区

手动安装不太明白... 是重新进入到安装流程? 需要手动进行下一步?

**Comment by bin456789** [comment]
试下就知道了

**Comment by bin456789** [comment]
我在azure arm上安装ubuntu 20.04 也进入了initramfs
原因是ubuntu initramfs没有对应的磁盘驱动器驱动
造成无法找到硬盘上的iso文件
这时只能重新安装系统

假如一开始用--ci参数安装的话，就没这个问题
