### ISSUE TITLE
移动云电脑装完Linux，无法连接网络

### ISSUE THREAD

**Issue by jjjdsdsf** [bin456789/reinstall#61]
![Screenshot_2024-02-26-15-25-18-860_cm komect aqb android cloudcomputermobile](https://github.com/bin456789/reinstall/assets/54743456/09ac4d5e-7ca4-4200-b867-a10f63ed593a)
![Screenshot_2024-02-26-15-19-46-647_com tencent mm](https://github.com/bin456789/reinstall/assets/54743456/49ce0798-853a-4561-b07d-88949901a992)

**Comment by bin456789** [comment]
cat /etc/resolv.conf
ping 114.114.114.114

**Comment by jjjdsdsf** [comment]
![Uploading Screenshot_2024-02-26-15-36-21-776_cm.komect.aqb.android.cloudcomputermobile.jpg…]()

**Comment by jjjdsdsf** [comment]
![Screenshot_2024-02-26-15-36-21-776_cm komect aqb android cloudcomputermobile](https://github.com/bin456789/reinstall/assets/54743456/ba70f2b7-ca0b-4627-94e5-9cf48d86bc7b)

**Comment by jjjdsdsf** [comment]
![Screenshot_2024-02-26-16-06-47-426_cm komect aqb android cloudcomputermobile](https://github.com/bin456789/reinstall/assets/54743456/82fb02aa-dbcd-437f-922d-e6d5aee35191)

**Comment by bin456789** [comment]
那修改 /etc/networkmanager/system-connections/里面的文件

**Comment by jjjdsdsf** [comment]
![Uploading Screenshot_2024-02-26-16-47-38-421_com.tencent.mm.jpg…]()

**Comment by bin456789** [comment]
我记错了，是 /etc/netplan/50-cloud-init.yaml

**Comment by jjjdsdsf** [comment]
![Uploading Screenshot_2024-02-26-17-04-57-458_cm.komect.aqb.android.cloudcomputermobile.jpg…]()

**Comment by jjjdsdsf** [comment]
这个文件也没看出来有啥问题啊😭😭😭😭

**Comment by jjjdsdsf** [comment]
![Uploading Screenshot_2024-02-26-17-04-57-458_cm.komect.aqb.android.cloudcomputermobile.jpg…]()

**Comment by jjjdsdsf** [comment]
![Uploading mmexport1708938733601.jpg…]()

**Comment by bin456789** [comment]
添加 routes
```
network:
  ethernets:
    eth0:
      [...]
      routes:
        - to: default
          via: 172.23.0.1
          on-link: true
```
然后 netplan apply

**Comment by jjjdsdsf** [comment]
![Uploading Screenshot_2024-02-26-17-47-49-489_cm.komect.aqb.android.cloudcomputermobile.jpg…]()

**Comment by jjjdsdsf** [comment]
nameservers:
addresses: - 119.29.29.290%48ms - 223.5.5.5 routes:
- to: default via: 172.23.0.1 on -link: true set-name: eth0
"/etc/netplan/50-cloud-init.yaml"23L，768B written root@localhost:/etc/NetworkManager# netplan apply
** (generate:506): WARNING **: 01:44:17.369: Permissions for /etc/netplan/50-clo ud-init.yaml are too open. Netplan configuration should NOT be accessible by oth ers.
/etc/netplan/50-cloud-init.yaml:21:17:Invalid YAML: did not find expected '-' i ndicator:
via: 172.23.0.1
rootelocalhost:/etc/NetworkManager# ping 114.114.114.114 ping: connect: Network is unreachable
rootelocalhost:/etc/NetworkManager# ping baidu.com ping: baidu.com: Name or service not known rootelocalhost:/etc/NetworkManager#

**Comment by jjjdsdsf** [comment]
nameservers:
addresses: - 119.29.29.290
 - 223.5.5.5 
 routes:
- to: default
- via: 172.23.0.1 
- on -link: true 
- set-name: eth0
- 
"/etc/netplan/50-cloud-init.yaml"23L，768B written
 root@localhost:/etc/NetworkManager# netplan apply
** (generate:506): WARNING **: 01:44:17.369: Permissions for /etc/netplan/50-clo ud-init.yaml are too open. Netplan configuration should NOT be accessible by oth ers.
/etc/netplan/50-cloud-init.yaml:21:17:Invalid YAML: did not find expected '-' i ndicator:
via: 172.23.0.1
rootelocalhost:/etc/NetworkManager# ping 114.114.114.114 ping: connect: Network is unreachable
rootelocalhost:/etc/NetworkManager# ping baidu.com ping: baidu.com: Name or service not known rootelocalhost:/etc/NetworkManager#

**Comment by bin456789** [comment]
50-cloud-init.yaml 文件缩进有问题

**Comment by jjjdsdsf** [comment]
![Uploading IMG_20240226_182154.jpg…]()

**Comment by bin456789** [comment]
删除gateway4这一行

**Comment by jjjdsdsf** [comment]
![Uploading IMG_20240226_185205.jpg…]()

**Comment by jjjdsdsf** [comment]
现在只有四个警告，但是还是不能联网

**Comment by bin456789** [comment]
那我就不懂了

**Comment by jjjdsdsf** [comment]
😭😭😭😭难搞，看不懂为啥不能联网

**Comment by jjjdsdsf** [comment]
大佬，这脚本里支持的Linux有带图形界面的吗

**Comment by bin456789** [comment]
没有

**Comment by jjjdsdsf** [comment]
大佬，装Ubuntu有网了，arch和Debian没网，其他的没试

**Comment by bin456789** [comment]
这台机用了 onlink 网关
目前 cloud-init 有bug，无法正确宣传这种情况
因此无法上网

现在脚本对这种情况做了修补
应该安装什么系统都有网了

**Comment by jjjdsdsf** [comment]
好的，晚上下班回去我在安装看看
