### ISSUE TITLE
移动云电脑下载一天有个插件好像是重试次数上限了

### ISSUE THREAD

**Issue by sunuuc** [bin456789/reinstall#62]
<img width="616" alt="Snipaste_2024-02-27_16-25-40" src="https://github.com/bin456789/reinstall/assets/77818773/fce7ac9f-c819-460c-9df7-88116b9331f9">

请问怎么办

**Comment by bin456789** [comment]
网络问题，无解，建议重置云电脑
无法重置的话，可以重装成alpine
```
umount -R /os
setup-alpine
```

**Comment by bin456789** [comment]
现在不用下载几百M的驱动了，这种情况应该不会发生了
