### ISSUE TITLE
请教一下, 如果从windows重装到linux,是否可以自定义重装完成以后的执行命令?

### ISSUE THREAD

**Issue by dev-kang** [bin456789/reinstall#64]
比如说,重装完成以后, 设置一个固定的计划任务或者安装一下哪吒监控的agent

**Comment by bin456789** [comment]
没有这个功能
不过你可以改 cloud-init.yaml，在runcmd里面下载运行你的脚本

要用 --ci 安装才有效

**Comment by JerFree** [comment]
好的,目前已经在cloud-init.yaml文件中实现这个功能感谢.
