### ISSUE TITLE
Windows下运行reinstall.bat ubuntu --ci出错

### ISSUE THREAD

**Issue by jjjdsdsf** [bin456789/reinstall#65]
![Uploading IMG_20240302_120740.jpg…]()

**Comment by jjjdsdsf** [comment]
![Uploading IMG_20240302_120740.jpg…]()

**Comment by bin456789** [comment]
图片没上传成功

**Comment by jjjdsdsf** [comment]
![Uploading IMG_20240302_120740.jpg…]()

**Comment by jjjdsdsf** [comment]
vm:true
微信 x Totalx Received x Xferd DOWNLOAD UMLNUZ AND INITRD http://nirrors.tuna.tsinghua.edu.cn/alpine/v3.19/releases/x86_64/nethoot/unlinnz-virt Average Speed Tine Time Tine Current.
100 9.8M 100 9.8M08725k Dload Upload Total0:00:01 0:00:01 Spent --:--:--8236k Left Speed
0
x Total100 8332k 100 8332k0 x Received % Xferd Average Speed5867k Dload Upload100....tsighua.edu.cn/alpine/v3.19/releases/x86_64/nethoot/initranfs-virt0 0:00:01 Tine Total Tine0:00:01 Spent -:--:-- 5875k Left Speed Time Current
*MOD ALPINE INITRD
x Total移动公or.con/hin456789/re installanain/trans. x Received % Xferd Average Speed Dload Upload Time Total Time Spent Time Left Speed Current
15612	0	0	0--:--:-- --:--:	
curl: <22) The requested URL returned error: 403 Error: Line ?2 return 22
command curl --insecure --connect-timeout 10 --retry 5 --retry-delay1 -f "$@" C:\Users\Administrator\Desktop>.
印象笔记	Cygwin64	
Temminal

**Comment by jjjdsdsf** [comment]
这图片不知道咋回事，一直这样

**Comment by jjjdsdsf** [comment]
![IMG_20240302_120740](https://github.com/bin456789/reinstall/assets/54743456/759c18fb-be5a-4f01-a1d1-0ff31a1f2bf5)

**Comment by jjjdsdsf** [comment]
![Uploading Screenshot_2024-03-02-16-59-24-698_com.tencent.mm.jpg…]()

**Comment by jjjdsdsf** [comment]
![Uploading Screenshot_2024-03-02-16-59-24-698_com.tencent.mm.jpg…]()

**Comment by jjjdsdsf** [comment]
![Screenshot_2024-03-02-16-59-24-698_com tencent mm](https://github.com/bin456789/reinstall/assets/54743456/b4b18a41-5c26-4ecb-b10b-ccf71915f142)

**Comment by bin456789** [comment]
好像是国内代理出了问题
但我这边没问题
可能代理屏蔽了你的网段

curl -LO https://raw.gitmirror.com/bin456789/reinstall/main/ttys.sh

试下能不能下载

**Comment by jjjdsdsf** [comment]
那应该没问题了，还有就是，大佬，我试着安装centos，安装完应该是grub配置出错了，我记得第一次重启进centos在重启就进Windows了，第二次就是重启就提示booting from hard disk了

**Comment by bin456789** [comment]
> 那应该没问题了，还有就是，大佬，我试着安装centos，安装完应该是grub配置出错了，我记得第一次重启进centos在重启就进Windows了，第二次就是重启就提示booting from hard disk了

啥？？

**Comment by jjjdsdsf** [comment]
![Uploading Screenshot_2024-03-02-17-32-09-748_cm.komect.aqb.android.cloudcomputermobile.jpg…]()

**Comment by jjjdsdsf** [comment]
![Screenshot_2024-03-02-17-32-09-748_cm komect aqb android cloudcomputermobile](https://github.com/bin456789/reinstall/assets/54743456/f596dc58-ff7d-42c8-a2a9-0e74ac41c077)

**Comment by jjjdsdsf** [comment]
这是装centos会出现这个

**Comment by bin456789** [comment]
不清楚，没遇到过

**Comment by jjjdsdsf** [comment]
😭😭😭怎么感觉我用起来一堆问题
