### ISSUE TITLE
windows系统dd别的windows系统出现问题，看日志好像是镜像站的文件不存在

### ISSUE THREAD

**Issue by wwyxdg** [bin456789/reinstall#66]
![图片](https://github.com/bin456789/reinstall/assets/47732104/2d929457-bd15-44ba-9e3f-aa61c8d9ab6e)
看日志是有几个文件404
setup文件应该是日志把，我临时把镜像源改成中科大了的，好像也能用，，
[setup.log](https://github.com/bin456789/reinstall/files/14546012/setup.log)

**Comment by bin456789** [comment]
谢谢反馈
现在又正常了
