### ISSUE TITLE
mirror.nju.edu.cn上面部分资源失效，无法访问

### ISSUE THREAD

**Issue by whooc** [bin456789/reinstall#67]
错误如下：
HTTP status 404 fetching http://mirror.nju.edu.cn/sourceware/cygwin/x86_64/release/xz/liblzma5/liblzma5-5.6.1-1.tar.zst
HTTP status 404 fetching http://mirror.nju.edu.cn/sourceware/cygwin/x86_64/release/xz/xz-5.6.1-1.tar.zst
download error in unattended_mode: 4 retries remaining.
download error in unattended_mode: 3 retries remaining.
download error in unattended_mode: 2 retries remaining.
download error in unattended_mode: 1 retry remaining.
download error in unattended_mode: out of retries
大佬帮忙，看看

**Comment by bin456789** [comment]
现在链接正常

**Comment by wwyxdg** [comment]
> 现在链接正常

大佬有考虑用别的镜像站作为备选下载方式嘛
