### ISSUE TITLE
MOD ALPINE INITRD

### ISSUE THREAD

**Issue by nimageji8** [bin456789/reinstall#69]
***** MOD ALPINE INITRD *****
rm: cannot remove '/tmp/reinstall/dev/console': Operation not permitted
rm: cannot remove '/tmp/reinstall/dev/null': Operation not permitted
Error: Line 1390 return 1
    rm -rf $dir

**Comment by bin456789** [comment]
windows文件管理器删除c:\cygwin\tmp\reinstall
再删除 reinstall.sh

重新运行脚本
