### ISSUE TITLE
更新了之后 阿里云2H2G好像就不能用了 一直连不上

### ISSUE THREAD

**Issue by charlesouwen** [bin456789/reinstall#70]
大佬能给看看么 刚需阿里云dd   windows

**Comment by bin456789** [comment]
阿里云有vnc，看下是什么情况

**Comment by charlesouwen** [comment]
我的这个服务器木有VNC 是其他渠道的  只有 IP 账户密码  咋看，昨天下午3点多还装了一台可以用  今天早上   就不行了   也能跑完  但是远程桌面链接的时候 就一直连不上了  一样的命令

**Comment by charlesouwen** [comment]
curl -O https://raw.gitmirror.com/bin456789/reinstall/main/reinstall.sh
bash reinstall.sh windows \
     --iso 'https://drive.massgrave.dev/en-us_windows_10_enterprise_ltsc_2021_x64_dvd_d289cf96.iso' \
     --image-name 'Windows 10 Enterprise LTSC 2021'

就这个

**Comment by charlesouwen** [comment]
![图片](https://github.com/bin456789/reinstall/assets/22210086/a245519c-378a-4ab4-81a8-19ff79f63d08)
![图片](https://github.com/bin456789/reinstall/assets/22210086/027c538d-8362-434d-bcfb-8ef06daba3d2)
这里运行都没问题 重启之后  就一直3389连不上

**Comment by charlesouwen** [comment]
大佬 你有空看看 就行   不太好意思 这么打扰你

**Comment by charlesouwen** [comment]
啊  我刚刚 又重新弄了 又可以了 抱歉大佬 我下次多测试测试
