### ISSUE TITLE
您好！汇报一个微小的BUG，CentOS网卡名和配置名不一致。alma正常。

### ISSUE THREAD

**Issue by GiT0WOalVjZ6ZhToNFeqLpdYByfodiQ4nksWmTL** [bin456789/reinstall#74]
CentOS Stream 9 系统中有一个微小的BUG，网卡名和配置名不一致。内存中ip、ifconfig命令获取的网卡名为eth0，但网卡配置名为ens3.nmconnection 。虽不影响系统正常使用，但有些程序要读取网卡配置文件可能就会报错。AlmaLinux系统一切正常。

最后，感谢作者的一键重装脚本，非常好用，是Moeclub脚本之后的新的高度。

下图是CentOS Stream 9：
![CS9](https://github.com/bin456789/reinstall/assets/67900373/b3c65538-8193-4290-9a7f-60c64ffda399)

下图是AlmaLinux9的：
![A9](https://github.com/bin456789/reinstall/assets/67900373/9894555f-d537-4c13-8757-2676b7a8f801)

**Comment by bin456789** [comment]
真正的配置文件在 /etc/sysconfig/network-scripts/ifcfg-eth0


而 centos9 ens3.nmconnection 和 alma9 ens0.nmconnection 都是镜像自带的文件，附上镜像链接
https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2

我在lightsail开了台centos9发现也是有ens3.nmconnection，但它没有ens3这个网卡，它的网卡是ens5

**Comment by GiT0WOalVjZ6ZhToNFeqLpdYByfodiQ4nksWmTL** [comment]
感谢解疑！看来是CentOS的锅。根据RHEL9官方说明书，红帽已将ifcfg方式标记“废弃”，建议从传统的ifcfg文件更新到NetworkManager，未来系统的ifcfg配置文件可能被废弃无法再用了，而只能用/etc/NetworkManager/system-connections/example.nmconnection 文件了。配置和管理网络说明书第37节说：

37.5. 将 NetworkManager 配置集从 ifcfg 迁移到 keyfile 格式
如果您仍然使用已弃用的 ifcfg 格式的连接配置文件，您可以将它们转换为 keyfile 格式。

根据连接配置文件的目的，将其保存在以下目录中：
/etc/NetworkManager/system-connections/ ：持久配置文件的位置。如果您使用 NetworkManager API 修改了持久配置文件，NetworkManager 会写并覆盖此目录中的文件。

https://access.redhat.com/documentation/zh-cn/red_hat_enterprise_linux/9/html-single/configuring_and_managing_networking/index#configuring-ethtool-settings-in-networkmanager-connection-profiles_configuring-and-managing-networking

**Comment by bin456789** [comment]
现在脚本会删除镜像自带的网络配置
然而cloud-init 还是选择将配置放在 /etc/sysconfig/network-scripts/
可能有其他考量吧，就不修改了

**Comment by GiT0WOalVjZ6ZhToNFeqLpdYByfodiQ4nksWmTL** [comment]
多谢！自从Ubuntu移民到红帽家族后，对RHEL/CentOS真是越用越舒服。
