### ISSUE TITLE
最新版dd 甲骨文amd 机器失败？

### ISSUE THREAD

**Issue by debiansid** [bin456789/reinstall#75]
重启还是原来的系统

**Comment by debiansid** [comment]
close

**Comment by debiansid** [comment]
换了一个脚本可以了.

**Comment by bin456789** [comment]
所以是装什么系统

**Comment by debiansid** [comment]
alpine stable

**Comment by bin456789** [comment]
开了两台机，初始系统选 oracle linux 和 ubuntu，没发现问题

**Comment by debiansid** [comment]
> 开了两台机，初始系统选 oracle linux 和 ubuntu，没发现问题

我那机器先用萌咖脚本dd 成了D11 想换系统 本脚本不行，两台都跑过，换了另外一个就好了

**Comment by bin456789** [comment]
> > 开了两台机，初始系统选 oracle linux 和 ubuntu，没发现问题
> 
> 我那机器先用萌咖脚本dd 成了D11 想换系统 本脚本不行，两台都跑过，换了另外一个就好了

还是无法复现

**Comment by debiansid** [comment]
> > > 开了两台机，初始系统选 oracle linux 和 ubuntu，没发现问题
> > 
> > 
> > 我那机器先用萌咖脚本dd 成了D11 想换系统 本脚本不行，两台都跑过，换了另外一个就好了
> 
> 还是无法复现

我该在失败时候截图的 现在没环境了，谢谢您的时间.

**Comment by ohjust** [comment]
> > 开了两台机，初始系统选 oracle linux 和 ubuntu，没发现问题
> 
> 我那机器先用萌咖脚本dd 成了D11 想换系统 本脚本不行，两台都跑过，换了另外一个就好了
推荐几个甲骨文dd的脚本吧，还有甲骨文dd最好是有二个实例吗？
