### ISSUE TITLE
天翼云电脑DD失败

### ISSUE THREAD

**Issue by yanaxiao** [bin456789/reinstall#76]
执行安装或者DD WINODWS 提示这个错误，请问要如何处理？
![QQ截图20240502010524](https://github.com/bin456789/reinstall/assets/53174017/b9e3b8b6-3bfd-4896-81ff-2035b0203dbf)

**Comment by bin456789** [comment]
运行看看
`wmic logicaldisk where "DeviceID='C:'" assoc:value /resultclass:Win32_DiskPartition`

**Comment by yanaxiao** [comment]
运行 wmic logicaldisk where "DeviceID='C:'" assoc:value /resultclass:Win32_DiskPartition 后的显示。
![微信截图_20240502135500](https://github.com/bin456789/reinstall/assets/53174017/3a279a2d-6d8d-411f-afac-4f1f0cfd7222)

**Comment by bin456789** [comment]
你这图出现了两个主机名，很奇怪
看下 
`wmic /node:"XMYDN8C16G-h0LF" logicaldisk where "DeviceID='C:'" assoc:value /resultclass:Win32_DiskPartition`

**Comment by yanaxiao** [comment]
> 你这图出现了两个主机名，很奇怪 看下 `wmic /node:"XMYDN8C16G-h0LF" logicaldisk where "DeviceID='C:'" assoc:value /resultclass:Win32_DiskPartition`

```
Administrator@XMYDN8C16G-h0LF ~
$ wmic /node:"XMYDN8C16G-h0LF" logicaldisk where "DeviceID='C:'" assoc:value /resultclass:Win32_DiskPartition
Invalid Global Switch.

Administrator@XMYDN8C16G-h0LF ~
$
```

**Comment by yanaxiao** [comment]
![Uploading QQ截图20240502224646.png…]()

**Comment by yanaxiao** [comment]
![QQ截图20240502224646](https://github.com/bin456789/reinstall/assets/53174017/206021ba-ca71-4039-8715-383f86ac6f65)

**Comment by bin456789** [comment]
太奇怪了，暂时无法解决

**Comment by bin456789** [comment]
现在用了另一种方法，应该没问题了
