### ISSUE TITLE
求支持 自定义密码 和 自定义镜像源地址 和 自定义端口

### ISSUE THREAD

**Issue by ezrawic4j** [bin456789/reinstall#8]
谢谢

**Comment by ezrawic4j** [comment]
自定义密码最重要

**Comment by bin456789** [comment]
自定义密码/端口不打算支持
自定义镜像源应该也不会支持，因为红帽系会选择就近的源，debian是全球cdn，ubuntu是使用国家前缀的服务器
指定镜像源好像没太大必要

**Comment by ezrawic4j** [comment]
> 自定义密码/端口不打算支持 自定义镜像源应该也不会支持，因为红帽系会选择就近的源，debian是全球cdn，ubuntu是使用国家前缀的服务器 指定镜像源好像没太大必要

国内机器咋整呢 debian的官方源速度很慢的 大佬

**Comment by bin456789** [comment]
检查到是国内机，设置成使用 ftp.cn.debian.org
