### ISSUE TITLE
ubuntu怎么使用传统方式安装

### ISSUE THREAD

**Issue by Lqbxx** [bin456789/reinstall#80]
博主，您好请问怎么使用传统方式安装ubuntu系统，使用云镜像安装似乎有点问题，命令行是这样的吗 ubuntu24.04^

**Comment by bin456789** [comment]
传统模式安装 ubuntu 已经删除了
一来很多人不看说明，不会用 --ci 安装
二来传统安装对小内存不友好，对物理机也不友好

那个 ^ 只是说明一下是云镜像安装，没作用
加不了 --ci  都一样用云镜像

**Comment by Lqbxx** [comment]
但是云镜像安装缺少了很多依赖的软件，希望博主能把传统式安装回来

**Comment by bin456789** [comment]
用云镜像能安装就行，用的是官方minimal镜像，软件也是官方安排的

**Comment by Lqbxx** [comment]
但是安装进入桌面提示错误，所以我认为这个云镜像和传统方式安装都需要的

**Comment by bin456789** [comment]
你说的错误应该是指这几行
```
This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.
```

不过云服务大厂的 ubuntu minimal 都有这几行，这是正常的

**Comment by bin456789** [comment]
这就不关脚本事了，大概率大厂云的minimal镜像也是如此

实在不喜欢minimal镜像的话，可以这样
运行脚本后，最后几行会显示 custom.cfg 或者 grub.cfg 的路径和内容
手动改成完整版镜像链接就可以了
例如: https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img

**Comment by Forensax** [comment]
> 这就不关脚本事了，大概率大厂云的minimal镜像也是如此
> 
> 实在不喜欢minimal镜像的话，可以这样 运行脚本后，最后几行会显示 custom.cfg 或者 grub.cfg 的路径和内容 手动改成完整版镜像链接就可以了 例如: https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img

可以的话希望老哥添加一个启用完整版的选项

**Comment by bin456789** [comment]
现在默认安装完整版镜像
添加 --minimal 则安装 minimal 镜像

**Comment by Forensax** [comment]
> 现在默认安装完整版镜像 添加 --minimal 则安装 minimal 镜像

谢谢！
