### ISSUE TITLE
在移动云dd时提示can't find os partition

### ISSUE THREAD

**Issue by n1vag** [bin456789/reinstall#81]
政企云 在广州和郑州都这样

![1715060573171.png](https://img2.imgtp.com/2024/05/07/jFQSlOOf.png)

**Comment by bin456789** [comment]
这是添加 IP 配置失败，可以不用管，系统已经 D 上去了

**Comment by bin456789** [comment]
你这图最后显示 alpine 3.18，不是最新的脚本啊，最新的应该显示 3.19
