### ISSUE TITLE
DD 自定义 centos7 镜像出错

### ISSUE THREAD

**Issue by lufeiit** [bin456789/reinstall#82]
win server 2022 Hyper-v 第二代虚拟机环境 

DD 自定义 centos7 镜像出错

提示错误 (详细错误看图片)

**Error:Line 578 return 1**
     efi_row=$(lsblk /dev/$xda -ro NAME,PARTTYPE,PARTUUID I grep -i "SEFI_UUID")

![a8b3790456ffa8c21006144ea7a87130.png](https://i.mji.rip/2024/05/11/a8b3790456ffa8c21006144ea7a87130.png)
![963bcab0c49e3ad1e86a1aa6c886c389.png](https://i.mji.rip/2024/05/11/963bcab0c49e3ad1e86a1aa6c886c389.png)

**Comment by bin456789** [comment]
目测镜像不含efi分区
