### ISSUE TITLE
windows10 重装为 Ubuntu 22.04 报错

### ISSUE THREAD

**Issue by xcoder119** [bin456789/reinstall#83]
今天在win10设备上尝试运行 reinstall.bat ,重装为Ubuntu 22.04时出现以下报错，确认已经windows自带杀软和防火墙，应该是南京大学的源出问题了，作者大大能否修复一下，比如把下载源换成清华的？灰常感谢！！
![IMG_20240517_114129](https://github.com/bin456789/reinstall/assets/60035990/4b9427b1-0190-42a4-8b6d-d62d0a3f88e9)

**Comment by xcoder119** [comment]
确认已经windows自带杀软和防火墙

**Comment by xcoder119** [comment]
确认已经关闭了windows自带杀软和防火墙

**Comment by bin456789** [comment]
清华源没有这个镜像
之前反馈过，就是不肯添加
https://github.com/tuna/issues/issues/1788

我看南大源正在同步镜像

目前建议你手动修改桌面上的脚本第 826 行
https://github.com/bin456789/reinstall/blob/f60ec31e48cd1f06f805d889373ab8fd841f7507/reinstall.sh#L826

使用这个 daily 镜像
https://mirrors.tuna.tsinghua.edu.cn/ubuntu-cloud-images/minimal/daily/noble/current/noble-minimal-cloudimg-amd64.img

**Comment by xcoder119** [comment]
好的，感谢作者大大的解答，您的项目极大的减轻了我们运维人员的工作量，再次感谢您的无私付出和开源共享的精神！！

**Comment by bin456789** [comment]
上面链接是24.04的

22.04 是这个 https://mirrors.ustc.edu.cn/ubuntu-cloud-images/minimal/releases/jammy/release/ubuntu-22.04-minimal-cloudimg-amd64.img

**Comment by xcoder119** [comment]
好的，我已经看到了，谢谢您
