### ISSUE TITLE
谷歌云已经用不了？

### ISSUE THREAD

**Issue by zhaohai1024** [bin456789/reinstall#89]
以前云镜像模式能正常 dd
最近想重装系统这个新模式用不了？？

**Comment by bin456789** [comment]
能用啊

**Comment by zhaohai1024** [comment]
我装的是 debian 等了半个小时失联了
以前云镜像模式时候十几分钟就 dd 完成了
请问是什么问题吗？

**Comment by bin456789** [comment]
gcp免费机是慢，不过肯定能正常安装，你可以查看vnc观察进度

以前的云镜像类似dd，所以快
