### ISSUE TITLE
请教下Ubuntu如何在重装阶段安装指定软件包

### ISSUE THREAD

**Issue by wgetnz** [bin456789/reinstall#90]
如题，forked后修改confhome未自己的项目地址，然后在修改ubuntu.yaml的runcmd安装指定软件包

安装命令: apt update && apt install wget  aria2 curl git screen nmap lrzsz build-essential htop unzip vim net-tools nodejs rsync python3-pip openjdk-11-jdk -y 
重装后相关软件包没有安装在系统上，cloud-init.yaml也尝试了，但是都没有安装成功

重装命令是：curl -O https://raw.githubusercontent.com/wgetnz/reinstall/main/reinstall.sh && bash [reinstall.sh](https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh) ubuntu 22.04 && reboot

请教下有办法安装指定软件包吗

**Comment by bin456789** [comment]
放到 cloud-init.yaml 上是对的，ubuntu.yaml 已经不用了

至于为什么没安装成功，可以查下日志 /var/log/cloud-init*
