### ISSUE TITLE
ubuntu 20.04安装kali失败

### ISSUE THREAD

**Issue by Poison-CY** [bin456789/reinstall#91]
CloudCone的1c2g小鸡，原系统ubuntu 20.04，安装kali失败
![image](https://github.com/bin456789/reinstall/assets/155166943/a5d4ed47-cf05-4bf8-8367-8a68d6a8cfca)

**Comment by bin456789** [comment]
最近 kali initrd 删除了原版 wget，换成了 busybox wget ，不支持原来用的参数因此出现问题。这部分现已修复

但是经我测试 CloudCone 是无法使用本脚本的，因为用了外部 grub 引导，脚本未处理这种情况

**Comment by bin456789** [comment]
现在能在 CloudCone 上从 debian 安装 debian/kali
但是kali的ext4版本太新， CloudCone  的 grub 无法识别
需要在vnc grub 菜单中输入 c  exit <回车> 才能引导到 kali
