### ISSUE TITLE
阿里云轻量dd后二次重启进入紧急模式

### ISSUE THREAD

**Issue by hqycloud** [bin456789/reinstall#93]
ubuntu22.04
d完启动后正常，但手动reboot就会进入紧急模式，目前这个bug只在这个脚本上遇到过，其他的dd脚本没这个问题

**Comment by bin456789** [comment]
应该有错误提示吧？上个图？

**Comment by hqycloud** [comment]
没有明显的报错，估计要看系统日志才能看到，但是我已经用了其他dd脚本了

**Comment by hqycloud** [comment]
> 应该有错误提示吧？上个图？

要不我先关掉issue吧？等下次有空了再复现

**Comment by bin456789** [comment]
> > 应该有错误提示吧？上个图？
> 
> 要不我先关掉issue吧？等下次有空了再复现

ok
