### ISSUE TITLE
windows 安装过程提示报错

### ISSUE THREAD

**Issue by g2thub** [bin456789/reinstall#94]
环境：GCP基本所有基础机型都尝试了
报错内容：
An unknown command-line option [/ResizeRecoveryPartition] was specified
尝试安装的镜像：win11 pro， win 10 pro， win server 2022
出现在有关Diskpart 命令执行的时间点
猜测有关报错的commit来自 ed84ad3f3688eee23725b4e602726dd2a832a5e8

**Comment by bin456789** [comment]
你猜对了，先回滚了
