### ISSUE TITLE
curl: (22) The requested URL returned error: 403

### ISSUE THREAD

**Issue by 0x8001** [bin456789/reinstall#95]
移动云电脑DD 
只要访问http://mirrors.tuna.tsinghua.edu.cn就返回403是被屏蔽了吗
报错：curl: (22) The requested URL returned error: 403

**Comment by bin456789** [comment]
是的，有多个 issue 都反馈清华源403，正在考虑换成其他源

**Comment by 0x8001** [comment]
> 是的，有多个 issue 都反馈清华源403，正在考虑换成其他源

辛苦大佬，我等个更新

**Comment by bin456789** [comment]
更新了
