### ISSUE TITLE
windows server 2025 安装失败

### ISSUE THREAD

**Issue by copycodetest** [bin456789/reinstall#96]
采用：安装  Windows ISO方式安装。
安装命令： `bash reinstall.sh windows \
     --image-name 'Windows Server 2025 SERVERDATACENTER' \
     --iso 'https://drive.massgrave.dev/zh-cn_windows_server_2025_preview_x64_dvd_a12bb0bf.iso'`

错误信息如下：
![JuneFriday73813447](https://github.com/bin456789/reinstall/assets/117625182/1fa812cf-de05-49af-9d79-a1105fc04601)

**Comment by bin456789** [comment]
经测试 windows 11 24h2 / windows server 2025 使用的新版安装程序不会创建 BIOS MBR 引导
暂时用回旧版安装程序解决这一问题
