### ISSUE TITLE
大佬，想问下，能不能开发一个在1C 256M内存 3G硬盘上服务器能跑起来的OpenSUSE系统，最好能放到系统DD脚本里面，希望大佬能帮忙解决下这个问题

### ISSUE THREAD

**Issue by musicclub1563** [bin456789/reinstall#97]
大佬，想问下，能不能开发一个在1C 256M内存 3G硬盘上服务器能跑起来的OpenSUSE系统，最好能放到系统DD脚本里面

**Comment by bin456789** [comment]
好像现在就可以

**Comment by musicclub1563** [comment]
OKOK，谢谢大佬

**Comment by musicclub1563** [comment]
更新了以后麻烦说一下，麻烦了

**Comment by bin456789** [comment]
我这边测试现在能在256+3g上安装opensuse，即使不更新脚本

不过即使都是256m，不同机器可用内存也有差别

你可以先试下

**Comment by musicclub1563** [comment]
但是为啥这个系统无法被哪吒探针识别系统图标呢？无论是滚动版本还是Leap版本，希望大佬能给个Gentoo的系统，我在1C 256M 3G硬盘的服务器上面无法运行

**Comment by bin456789** [comment]
> 但是为啥这个系统无法被哪吒探针识别系统图标呢？无论是滚动版本还是Leap版本

这个问题你应该找哪吒探针

> 希望大佬能给个Gentoo的系统，我在1C 256M 3G硬盘的服务器上面无法运行

Gentoo 以编译著名，编译是很浪费内存的，所以 256+3g基本上无法用正常途径安装的，dd还有点可能
