### ISSUE TITLE
kvm的vps重装到Debian 12 网卡（驱动）配置失败？

### ISSUE THREAD

**Issue by Xiaodu233** [bin456789/reinstall#98]
硬件配置都符合要求，安装完成后在VNC使用 ‘ip addr’ 检查IP地址，原本网卡eth0消失，只剩lo，服务商是Racknerd。
请问是什么问题？

**Comment by bin456789** [comment]
lspci -nnk 看下是什么网卡

**Comment by bin456789** [comment]
这机器使用了 e1000网卡，云内核没有这个驱动

现在脚本更新了遇到 e1000网卡使用普通内核
