### ISSUE TITLE
为什么我装的 Alpine不能开swap？

### ISSUE THREAD

**Issue by mrjg117** [bin456789/reinstall#99]
su
dd if=/dev/zero of=/swapfile bs=1024 count=2097152
chmod 600 /swapfile
mkswap /swapfile
fstab+
/swapfile swap swap sw 0 0

重启后不会生效

**Comment by bin456789** [comment]
要在 Alpine Linux 上设置并启用交换文件，确保在创建和配置交换文件后进行了正确的步骤。你已经大部分都正确了，但可能在某些步骤中有遗漏或需要调整。这里是一个详细的指南：

### 1. 创建交换文件

```sh
dd if=/dev/zero of=/swapfile bs=1024 count=2097152
```

### 2. 设置交换文件的权限

```sh
chmod 600 /swapfile
```

### 3. 设置交换空间

```sh
mkswap /swapfile
```

### 4. 激活交换空间

```sh
swapon /swapfile
```

### 5. 编辑 `/etc/fstab` 文件

确保你在 `/etc/fstab` 文件中添加了以下内容：

```
/swapfile swap swap defaults 0 0
```

注意，你之前的 `fstab` 文件内容可能是：

```
/swapfile swap swap sw 0 0
```

其中 `sw` 应该被替换为 `defaults`。

### 6. 验证交换空间

重启系统后，可以通过以下命令验证交换空间是否启用：

```sh
free -h
```

你应该在输出中看到交换空间的大小。如果未生效，可以尝试以下步骤进行故障排除：

### 故障排除步骤

1. **检查交换文件的存在性**：确保重启后交换文件仍然存在。

   ```sh
   ls -lh /swapfile
   ```

2. **手动启用交换空间**：重启后手动启用交换空间，看是否能成功。

   ```sh
   swapon /swapfile
   ```

3. **检查 `/etc/fstab`**：确保 `/etc/fstab` 文件的格式正确，没有拼写错误。

   ```sh
   cat /etc/fstab
   ```

4. **日志文件**：检查系统日志文件以获取任何相关错误信息。

   ```sh
   dmesg | grep swap
   ```

通过上述步骤，你应该能够在 Alpine Linux 上成功配置和启用交换文件。如果问题依旧存在，可以提供更多的系统日志或错误信息，以便进一步诊断。

**Comment by mrjg117** [comment]
> 要在 Alpine Linux 上设置并启用交换文件，确保在创建和配置交换文件后进行了正确的步骤。你已经大部分都正确了，但可能在某些步骤中有遗漏或需要调整。这里是一个详细的指南：
> 
> ### 1. 创建交换文件
> ```shell
> dd if=/dev/zero of=/swapfile bs=1024 count=2097152
> ```
> 
> ### 2. 设置交换文件的权限
> ```shell
> chmod 600 /swapfile
> ```
> 
> ### 3. 设置交换空间
> ```shell
> mkswap /swapfile
> ```
> 
> ### 4. 激活交换空间
> ```shell
> swapon /swapfile
> ```
> 
> ### 5. 编辑 `/etc/fstab` 文件
> 确保你在 `/etc/fstab` 文件中添加了以下内容：
> 
> ```
> /swapfile swap swap defaults 0 0
> ```
> 
> 注意，你之前的 `fstab` 文件内容可能是：
> 
> ```
> /swapfile swap swap sw 0 0
> ```
> 
> 其中 `sw` 应该被替换为 `defaults`。
> 
> ### 6. 验证交换空间
> 重启系统后，可以通过以下命令验证交换空间是否启用：
> 
> ```shell
> free -h
> ```
> 
> 你应该在输出中看到交换空间的大小。如果未生效，可以尝试以下步骤进行故障排除：
> 
> ### 故障排除步骤
> 1. **检查交换文件的存在性**：确保重启后交换文件仍然存在。
>    ```shell
>    ls -lh /swapfile
>    ```
> 2. **手动启用交换空间**：重启后手动启用交换空间，看是否能成功。
>    ```shell
>    swapon /swapfile
>    ```
> 3. **检查 `/etc/fstab`**：确保 `/etc/fstab` 文件的格式正确，没有拼写错误。
>    ```shell
>    cat /etc/fstab
>    ```
> 4. **日志文件**：检查系统日志文件以获取任何相关错误信息。
>    ```shell
>    dmesg | grep swap
>    ```
> 
> 通过上述步骤，你应该能够在 Alpine Linux 上成功配置和启用交换文件。如果问题依旧存在，可以提供更多的系统日志或错误信息，以便进一步诊断。

按照你的操作试了下还是不行，日志输出：[    1.014277] Spectre V1 : Mitigation: usercopy/swapgs barriers and __user pointer sanitization

甲骨文的x64免费机  bash reinstall.sh alpine  安装的alpine， 也尝试了按照前边网友提示的 添加 rc-update add swap 。但还是同样不行。

**Comment by bin456789** [comment]
dd if=/dev/zero of=/swapfile bs=1024 count=2097152
chmod 600 /swapfile
mkswap /swapfile

echo '/swapfile swap swap sw 0 0' >>/etc/fstab

rc-update add swap

我测试了，没问题啊
